### ISSUE TITLE
Enforce H264 to support Safari 11

### ISSUE THREAD

**Issue by Zaid-Al-Omari** [versatica/mediasoup-client#10]
Can we have the option to enforce the use of H264 codec on all clients (chrome, edge, firefox) when a Safari 11 user joins, so that the safari user can see all videos instead of using a browser plug in.

you can look in this fiddle in order to enforce H264 codec
https://jsfiddle.net/rainzhao/s5tadxgq/

**Comment by ibc** [comment]
That is not mediasoup-client business. If you want that all the clients use H264 just set H264 as video codec in the mediasoup Room.

mediasoup-client will not "move" from VP8 to H264 as far as a Safari 11 user joins. If you want that behavior, develop your app to do that.
