### ISSUE TITLE
Audio not working on safari 13

### ISSUE THREAD

**Issue by spiderman22** [versatica/mediasoup-client#101]
Trying to use client on safari 13
Error regarding unified plan.

I understand that there was a fix for safari 12, and by looking at the code - it was supposed to fix all future versions of safari - in Device.js - returns handler for safari 11 (plan-b)

That doesn't seem to work.

**Comment by ibc** [comment]
Can you provide which error? Otherwise this report is useless.

**Comment by spiderman22** [comment]
Hardly useless as I pointed the exact place in the code where it fails, but here it is:

Unhandled Promise Rejection: InvalidAccessError: Failed to set remote offer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan.
inf-bundle.js:1:52531

**Comment by spiderman22** [comment]
BTW, this is what the browser is returning for user agent, browser (from parsing ua) and engine, as relied on in Device.js in detectDevice() method, line 50 or so:

user agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1`

browser:
```
browser: {name: "Safari", version: "12.0"}

engine: {name: "WebKit", version: "605.1.15"}

os: {name: "iOS", version: "12.1.3"}

platform: {type: "mobile", vendor: "Apple", model: "iPhone"
```
engine: `{name: "WebKit", version: "605.1.15"}`

It looks like safari 12, but in the safari about I am seeing version 13.0.4.
Another issue is that the fix in the code refers to version >=12.1, and this is 12.0

**Comment by ibc** [comment]
Just tested Safari 13.0.4 in Mojave with the mediasoup-demo and it works fine. Just ensure that your Safari has "WebRTC Unified-Plan" enabled in the "Develop" menu (this menu must be enabled in Preferences - Advanced):

<img width="782" alt="Screenshot 2019-12-19 at 17 21 13" src="https://user-images.githubusercontent.com/16191/71190095-36e18c00-2284-11ea-92cc-adc0c81763cb.png">

It's extremely hard to make it work in Safari is configured to run without Unified Plan when it's supposed to have it enabled.

**Comment by mihaa1** [comment]
Thanks for the quick response.
The Unified Plan feature is enabled, but the version returned by safari on both macOS and iOS we tested is 12.0, but the check in the code is for >=12.1.

Changing it to 12.0 seems to fix the issue.

**Comment by spiderman22** [comment]
Thanks for the quick response.
The Unified Plan feature is enabled, but the version returned by safari on both macOS and iOS we tested is 12.0, but the check in the code is for >=12.1.

Changing it to 12.0 seems to fix the issue.

**Comment by ibc** [comment]
So you mean iOS Safari, right? I'm afraid that if iOS Safari announces a different version in the UA that's a bug to report to Apple, isn't it? We did `>=12.1` because indeed `12.0` did not implement Unified-Plan properly in Safari desktop.

So let's clarify this please.

**Comment by spiderman22** [comment]
I am getting "wrong" version for safari on 2 devices:
* desktop - macOS Catalina 10.15.2. Safari version reported in about: 13.0.4
* iphone - iOS 13.3

I will check more devices asap.

Putting aside the reason for this version discrepancy- apple bug or not - would it be a better fix to not rely on the version but only on the next line:
`RTCRtpTransceiver.prototype.hasOwnProperty("currentDirection”);`

It is a condition in the code already, and also saw this here:
https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8/

i.e - first check if safari (any version) - and then decide on plan-b vs. unified plan using above line

**Comment by ibc** [comment]
I don't want to even enable `Safari12` handler (transceivers based) on Safari < 12.

Given your tests, would it work by just replacing `browser.satisfies({ safari: '>=12.1' })` with `browser.satisfies({ safari: '>=12.0' })`? In the past this was important but I assume nowadays all people have updated their Safari so, even if they still report 12.0 in the User-Agent, they would support transceiver if the other conditions are met. Thoughts?

**Comment by spiderman22** [comment]
I would like to test some more devices, but it seem to work

**Comment by ibc** [comment]
Done in 3.3.11
