### ISSUE TITLE
React Native handler: replaceTrack not implemented

### ISSUE THREAD

**Issue by fkapetanovic** [versatica/mediasoup-client#105]
```
sync replaceTrack(
		{ localId, track }: // eslint-disable-line @typescript-eslint/no-unused-vars
		{ localId: string; track: MediaStreamTrack }
	): Promise<never>
	{
		throw new UnsupportedError('not implemented');
	}
```

Is there a way to switch between front/back camera streams mid-call on React Native?

**Comment by ibc** [comment]
Please, questions in the mediasoup forum, not here. BTW read the docs of react-native-webrtc, it provides a custom way for that.

**Comment by fkapetanovic** [comment]
@ibc This did the trick. Thanks.

**Comment by ibc** [comment]
😉

**Comment by pritthishnath** [comment]
@fkapetanovic What is the trick?
