### ISSUE TITLE
Disconnecting publisher - muted value on track is not changed in safari

### ISSUE THREAD

**Issue by spiderman22** [versatica/mediasoup-client#106]
I am trying to support auto recover of subscriber when publisher refreshes his page and reconnects after some time.

In chrome, I managed to make this work, relying on
`consumer.track.muted`
property - which turns to true once the publisher disconnects.

This doesn't seem to work in safari - on either audio/video tracks.

1) As a general solution for what I am trying to achieve - is this the way to go?
2) Is there any way to achieve a similar solution in Safari?

**Comment by ibc** [comment]
Not here, please. Questions in the forum.
