### ISSUE TITLE
dtlsstatechange event not called with 'closed'

### ISSUE THREAD

**Issue by spiderman22** [versatica/mediasoup-client#107]
Hello,

I have a case where the event 'dtlsstatechange' is not called - when killing a program - e.g. chrome,
this event is not called.
When closing the tab/window - it does gets called.

I am relying on this to clear disconnected clients

**Comment by ibc** [comment]
Please, the browser will abruptly terminate everything if you kill it abruptly with zero chance for the app to react on it. This is how browsers and processes/programs in general work. No magic here. Make your server ALSO react on WebSocket disconnection.

Also, use the forum for usage questions, this is not a bug.
