### ISSUE TITLE
using 'mediasoup-client' with meteorjs

### ISSUE THREAD

**Issue by chetanbnaik** [versatica/mediasoup-client#11]
As mentioned [here](https://mediasoup.org/documentation/mediasoup-client/installation/), mediasoup-client is using ES6 syntax. With meteor 1.6+ version, the support to ES6 syntax is inbuilt. But I still get the following errors when I use "import { getDeviceInfo } from 'mediasoup-client'".

> Uncaught SyntaxError: Unexpected token import

 on Chrome and 

> SyntaxError: import declarations may only appear at top level of a module

on Firefox

**Comment by ibc** [comment]
This is fixed in 2.0.5 (released right now)
