### ISSUE TITLE
The order of m-lines in answer doesn't match order in offer. Rejecting answer.

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup-client#112]
Not often, but consistently in production we're seeing the following error:

```
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer."
```

From a few spot checks I've seen this only on Chrome but several versions:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36`
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.115`

Any reason why mediasoup-client would re-arrange the m-lines?

**Comment by ibc** [comment]
No idea which version you are using. Please specify it, explain whether this happens in a send or recv transport. Get logs in client side and paste the SDP offers and corresponding SDP answers. Also specify which `handler` mediasoup-client is detecting.

**Comment by artushin** [comment]
Version is 3.3.14.
This happens on the send transport.
Handler I assume is latest Chrome.

I haven't been able to repro to get sdp's logged, but I'll let you know if I do. You can close this if it's not worth investigating without the sdps and I can re-open when I have them.

**Comment by ibc** [comment]
`device.handlerName` tells you the handler in use. In addition, there have been some improvements since that version. Please upgrade to the latest 3.5.1.

**Comment by ibc** [comment]
This issue should not happen and I've not seen it recently. Let's close the issue. Please reopen if you get more info (enable debugging in mediasoup-client and try to get the calls to `setLocalDescription()` and `setRemoteDescription()`).
