### ISSUE TITLE
ReactNative error: device not supported

### ISSUE THREAD

**Issue by omidborjian** [versatica/mediasoup-client#113]
Thanks for creating this client. I'm having a strange issue. I just added the library to my ReactNative project with:

`Yarn add mediasoup-client`
in my package.json I have the right version of react-native-webrtc and the latest mediasoup-client, but as soon as I create and instance of the Device(). I get "device not supported"

```
in my package.json:
"mediasoup-client": "^3.5.4",
"react-native-webrtc": "^1.75.3",

```

I took a look at your commits and i see the block where you check ReacNative in Device.ts, but still no luck... any idea what might be the cause?

The problematic block:
```
import { Device } from 'mediasoup-client';
const device = new Device();
```

**Comment by omidborjian** [comment]
Never mind. I followed the example and didn't realized you could pass in a handler.

Problem resolved with :

`const device = new mediasoupClient.Device({ Handler: "ReactNative"});`

**Comment by ibc** [comment]
Please, even if you got it working, it's not working as expected. Let's not close the issue.

`ReactNative` handler should be autodetected without having to pass `Handler: "ReactNative"` in the `Device` constructor. This is the code that should (and it used to) detect React Native platform:

```js
if (typeof navigator === 'object' && navigator.product === 'ReactNative')
{
	if (typeof RTCPeerConnection === 'undefined')
	{
		logger.warn(
			'this._detectDevice() | unsupported ReactNative without RTCPeerConnection');

			return undefined;
	}

	logger.debug('this._detectDevice() | ReactNative handler chosen');

	return 'ReactNative';
}
```

* Can you investigate why it does not detect React Native?
* Perhaps you are loading/importing `react-native-webrtc` **after** creating the mediasoup-client `Device`?
* Can you check this condition in React Native?: `typeof navigator === 'object' && navigator.product === 'ReactNative'`.
* Can you check this condition at the same time you create the `Device` instance?: `typeof RTCPeerConnection === 'undefined'`

**Comment by omidborjian** [comment]
Sounds good. I did some further investigation and this is what I found:

1. Here is my imports block:
```
import * as React from 'react';
import { StyleSheet, Text, View, TouchableOpacity, Dimensions, StatusBar, DeviceEventEmitter } from 'react-native';
import WebRTCLib, {
  RTCPeerConnection,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCView,
  MediaStream,
  MediaStreamTrack,
  mediaDevices,
  registerGlobals,
} from 'react-native-webrtc';
import Store from '../../components/Store'
import protooClient from 'protoo-client';
import * as mediasoupClient from 'mediasoup-client';
```

2. I put a console.error(navigator.product) inside the `if (typeof navigator === 'object' && navigator.product === 'ReactNative')` and it showed `ReactNative` so that's not the issue.

3. RTCPeerConnection was undefined which seemed to cause the issue. This is how I tested for it:
```
componentDidMount() {
console.error(typeof RTCPeerConnection === 'undefined')
this._device = new mediasoupClient.Device();

}
```
On a related note, after getting passed the Device instantiation, I had to import the `react-native-webrtc` in the ReactNative.js handler to make everything work. Otherwise I would get "MediaStream" is undefined, which is in this line:

`this._sendStream = new MediaStream();`

Hope that's helpful

**Comment by ibc** [comment]
Ok, got it. You need to call [registerGlobals()](https://github.com/react-native-webrtc/react-native-webrtc#registerglobals) for mediasoup-client to detect `react-native-webrtc`. I'll document it in the website.

**Comment by omidborjian** [comment]
Oh got it. That'd be great. Thanks again
