### ISSUE TITLE
Safari 11: iOS 11-11.2 Syntax Error

### ISSUE THREAD

**Issue by ethand91** [versatica/mediasoup-client#115]
When trying to use mediasoup with iOS 11-11.2, the following syntax error occurs:

```
SyntaxError: Unexpected token '...'. Expected a property name.
```

It seems that iOS 11-11.2 does not support the spread operator (...additionalSettings):
https://caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_object_literals

**Comment by ibc** [comment]
Yep, but this is not a mediasoup-client issue. mediasoup-client issue is written in modern TypeScript and produces modern ECMAScript. It is up to the application to transpile the whole app code (including node_modules libraries) to older ECMAScript.
