### ISSUE TITLE
Chrome 49 Support

### ISSUE THREAD

**Issue by erencay** [versatica/mediasoup-client#117]
Chrome 49 is the latest supported version for Windows XP and there are users likes to use XP. I created a Chrome49 handler for this and it looks like working for a while now. @ibc Would you like to add this handler to project?

**Comment by ibc** [comment]
How is that different from current Chrome56 handler (which is the lowest one right now)?

**Comment by erencay** [comment]
Chrome55 handler uses the new Webrtc syntax in functions, like;

`
const offer = await pc.createOffer({
    offerToReceiveAudio: true,
    offerToReceiveVideo: true
});
`

which are not supported by Chrome 49. I ported those functions to be compatible with the older (callback) syntax;
`pc.createOffer(successCallback, failureCallback, {
    offerToReceiveAudio: true,
    offerToReceiveVideo: true
})  `

**Comment by ibc** [comment]
I see. Ok, send a PR if you wish. Closing this issue. Thanks.
