### ISSUE TITLE
Pure html example

### ISSUE THREAD

**Issue by Jalseng** [versatica/mediasoup-client#12]
Hi, I'm interested in this sdk. Mediasoup is very nice and it's exactly what I wanted to use.
By the way, I wonder if there is a very simple example using <script src="mediasoup-client.js"/> and its API.
I tried to find it but I've got only mediasoup-client.js. 
Could you please give me any advice about this? Thank you.

**Comment by ibc** [comment]
The usage is the same no matter how do you load the `mediasoup-client` library:

https://mediasoup.org/documentation/mediasoup-client/installation/#usage

BTW: let's please use the mediasoup public mailing list for questions.
