### ISSUE TITLE
Please Help me to Fix device.load() TypeError

### ISSUE THREAD

**Issue by nodejscss** [versatica/mediasoup-client#120]
When I do device.load(routerRtpCapabilities), throw an TypeError in browser console, say: 
"
TypeError: caps is not an object
...
"

//------------------------------------------
The following is server side code:

worker = await mediasoup.createWorker(
							{
								logLevel   : config.mediasoup.workerSettings.logLevel,
								logTags    : config.mediasoup.workerSettings.logTags,
								rtcMinPort : Number(config.mediasoup.workerSettings.rtcMinPort),
								rtcMaxPort : Number(config.mediasoup.workerSettings.rtcMaxPort)
							});
					const { mediaCodecs } = config.mediasoup.routerOptions;
					const rtpCapabilities = mediasoup.getSupportedRtpCapabilities();
			    console.log(rtpCapabilities);

					// Create a mediasoup Router.
					const mediasoupRouter = await worker.createRouter({ mediaCodecs });

					console.log(mediasoupRouter.rtpCapabilities);

					signaling.emit(mediasoupRouter.rtpCapabilities);

//---------------------------------

client side code:

import { Device } from 'mediasoup-client';
import mySignaling from './my-signaling'; // Our own signaling stuff.

try {
  // Create a device (use browser auto-detection).
  const device = new Device();

  // Communicate with our server app to retrieve router RTP capabilities.
  const routerRtpCapabilities = await mySignaling.request('getRouterCapabilities');
  console.log(routerRtpCapabilities); // see the following log
  // Load the device with the router RTP capabilities.
  await device.load({ routerRtpCapabilities }); // throw TypeError
}
catch (e) {
  console.log(e);
}

// console.log(routerRtpCapabilities in browser:
codecs: Array(9)
0: {kind: "audio", mimeType: "audio/opus", clockRate: 48000, channels: 2, rtcpFeedback: Array(1), …}
1: {kind: "video", mimeType: "video/VP8", clockRate: 90000, rtcpFeedback: Array(5), parameters: {…}, …}
2: {kind: "video", mimeType: "video/rtx", preferredPayloadType: 102, clockRate: 90000, parameters: {…}, …}
3: {kind: "video", mimeType: "video/VP9", clockRate: 90000, rtcpFeedback: Array(5), parameters: {…}, …}
4: {kind: "video", mimeType: "video/rtx", preferredPayloadType: 104, clockRate: 90000, parameters: {…}, …}
5: {kind: "video", mimeType: "video/H264", clockRate: 90000, parameters: {…}, rtcpFeedback: Array(5), …}
6: {kind: "video", mimeType: "video/rtx", preferredPayloadType: 106, clockRate: 90000, parameters: {…}, …}
7: {kind: "video", mimeType: "video/H264", clockRate: 90000, parameters: {…}, rtcpFeedback: Array(5), …}
8: {kind: "video", mimeType: "video/rtx", preferredPayloadType: 108, clockRate: 90000, parameters: {…}, …}
length: 9
__proto__: Array(0)
headerExtensions: Array(13)
0: {kind: "audio", uri: "urn:ietf:params:rtp-hdrext:sdes:mid", preferredId: 1, preferredEncrypt: false, direction: "sendrecv"}
1: {kind: "video", uri: "urn:ietf:params:rtp-hdrext:sdes:mid", preferredId: 1, preferredEncrypt: false, direction: "sendrecv"}
2: {kind: "video", uri: "urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id", preferredId: 2, preferredEncrypt: false, direction: "recvonly"}
3: {kind: "video", uri: "urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id", preferredId: 3, preferredEncrypt: false, direction: "recvonly"}
4: {kind: "audio", uri: "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time", preferredId: 4, preferredEncrypt: false, direction: "sendrecv"}
5: {kind: "video", uri: "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time", preferredId: 4, preferredEncrypt: false, direction: "sendrecv"}
6: {kind: "audio", uri: "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01", preferredId: 5, preferredEncrypt: false, direction: "recvonly"}
7: {kind: "video", uri: "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01", preferredId: 5, preferredEncrypt: false, direction: "sendrecv"}
8: {kind: "video", uri: "http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07", preferredId: 6, preferredEncrypt: false, direction: "sendrecv"}
9: {kind: "video", uri: "urn:ietf:params:rtp-hdrext:framemarking", preferredId: 7, preferredEncrypt: false, direction: "sendrecv"}
10: {kind: "audio", uri: "urn:ietf:params:rtp-hdrext:ssrc-audio-level", preferredId: 10, preferredEncrypt: false, direction: "sendrecv"}
11: {kind: "video", uri: "urn:3gpp:video-orientation", preferredId: 11, preferredEncrypt: false, direction: "sendrecv"}
12: {kind: "video", uri: "urn:ietf:params:rtp-hdrext:toffset", preferredId: 12, preferredEncrypt: false, direction: "sendrecv"}
length: 13

**Comment by ibc** [comment]
Ask in the forum, not here, and I'll tell you the issue.

**Comment by maxz961** [comment]
Try to replace `device.load(routerRtpCapabilities)` for `device.load({ routerRtpCapabilities })`

**Comment by Ksj14-kumar** [comment]
basically, this error occurs due to passing a null or undefined value of routerRtpCapabilities in a device.load({ routerRtpCapabilities })
