### ISSUE TITLE
Dist mediasoup-client.js for 2.4.12 is still showing version 2.4.10.

### ISSUE THREAD

**Issue by Demodian** [versatica/mediasoup-client#121]
What is the "build" process to run the "gulp dist:production" script/task manually?  We are currently trying to use v2 for a project and do not have the time to fully research v3.  We are getting bit by the Firefox issue as in #104, but dist in GitHub is still at 2.4.10.

**Comment by ibc** [comment]
Questions in the forum, please.

**Comment by Demodian** [comment]
v2 dist file needs updating to 2.4.12 in GitHub.

**Comment by ibc** [comment]
pushed

**Comment by Demodian** [comment]
Thanks
