### ISSUE TITLE
Won't work without Webpack

### ISSUE THREAD

**Issue by nym21** [versatica/mediasoup-client#128]
Hi !

I'm trying to use the library with other bundlers (`rollup` via `vite`) but it isn't browser friendly, you guys use a ton a libraries that need node built-ins like `os`, `tty` and `util`.

Is it something that you plan to fix ?

Thank you !

**Comment by ibc** [comment]
Please use the mediasoup forum for questions. This is not a bug (mediasoup-client does not require on `os` or `tty` at all).

**Comment by nym21** [comment]
Not directly but it uses libraries such as `debug`

**Comment by ibc** [comment]
Please open a topic in the forum by explaining why that's problematic, we just use GitHub for bugs, not for discussions.
