### ISSUE TITLE
VP9 profile-id type should be string instead of int

### ISSUE THREAD

**Issue by binxie33** [versatica/mediasoup-client#129]
In webrtc source code, the function **SupportedVP9Codecs** return VP9 profile-id as string

```
std::vector<SdpVideoFormat> SupportedVP9Codecs() {
#ifdef RTC_ENABLE_VP9
  // Profile 2 might not be available on some platforms until
  // https://bugs.chromium.org/p/webm/issues/detail?id=1544 is solved.
  static bool vpx_supports_high_bit_depth =
      (vpx_codec_get_caps(vpx_codec_vp9_cx()) & VPX_CODEC_CAP_HIGHBITDEPTH) !=
          0 &&
      (vpx_codec_get_caps(vpx_codec_vp9_dx()) & VPX_CODEC_CAP_HIGHBITDEPTH) !=
          0;

  std::vector<SdpVideoFormat> supported_formats{SdpVideoFormat(
      cricket::kVp9CodecName,
      {{kVP9FmtpProfileId, VP9ProfileToString(VP9Profile::kProfile0)}})};
  if (vpx_supports_high_bit_depth) {
    supported_formats.push_back(SdpVideoFormat(
        cricket::kVp9CodecName,
        {{kVP9FmtpProfileId, VP9ProfileToString(VP9Profile::kProfile2)}}));
  }
  return supported_formats;
#else
  return std::vector<SdpVideoFormat>();
#endif
}
```

But mediasoup treat profile-id as int, it causes problem with native webrtc client that using VP9 because the VP9 codec match in mediasoup **matchCodecs** function is doing a **!==** comparison, which compare type as well.

```
case 'video/vp9':
		{
			// If strict matching check profile-id.
			if (strict)
			{
				const aProfileId = aCodec.parameters['profile-id'] || 0;
				const bProfileId = bCodec.parameters['profile-id'] || 0;

				if (aProfileId !== bProfileId)
					return false;
			}

			break;
		}
```

in mediasoup-client **extractRtpCapabilities** function, it only convert **profile-level-id** to string, and leave profile-id as int

```
// Specials case to convert parameter value to string.
			if (parameters && parameters['profile-level-id'])
				parameters['profile-level-id'] = String(parameters['profile-level-id']);
```

**Proposed Fix**

Follow the webrtc convention to change profile-id to string. 

1. add the following codes to change profile-id to string in mediasoup-client **extractRtpCapabilities** function:

```
			if (parameters && parameters['profile-id'])
				parameters['profile-id'] = String(parameters['profile-id']);
```

2. Change mediasoup **matchCodecs** function for the default value:

```
case 'video/vp9':
		{
			// If strict matching check profile-id.
			if (strict)
			{
				const aProfileId = aCodec.parameters['profile-id'] || '0';  // change to string
				const bProfileId = bCodec.parameters['profile-id'] || '0'; // change to string

				if (aProfileId !== bProfileId)
					return false;
			}

			break;
		}
```

3. In the mediasoup-demo server config.example.js, change the VP9 setting's profile-id to string

```
				{
					kind       : 'video',
					mimeType   : 'video/VP9',
					clockRate  : 90000,
					parameters :
					{
						'profile-id'             : '2',  // change to string
						'x-google-start-bitrate' : 1000
					}
				},
```

**Comment by ibc** [comment]
libwebrtc exposes **all** codec parameters as strings. We cannot change everything just because how internal API in libwebrtc exposes things. In mediasoup we clearly document that VP9's `profile-id` is a **number**:

* https://mediasoup.org/documentation/v3/mediasoup/rtp-parameters-and-capabilities/#VP9

So you must take care in your client side app and produce `RtpParameters` that are valid for mediasoup. This is, `profile-idp  must be converted to number.

BTW: you can also take a look to how libmediasoupclient deals with this stuff by looking at its `ortc.cpp` file (in `getVP9ProfileId()` function).

**Comment by binxie33** [comment]
Understood. Will change our native app accordingly.
