### ISSUE TITLE
Mediasoup-client lib cannot be used as is without transpilation

### ISSUE THREAD

**Issue by ea167** [versatica/mediasoup-client#130]
Hello,

Among thousands of dependencies we use, Mediasoup-client is the only one that is not supported by recent browsers without transpilation. The lib seems to use JS that is too advanced even for recent browsers.

Setting, in Babel 7, target browsers as 
```
	"safari": 	"13",
	"edge": 	"81",
	"chrome": 	"81",
	"firefox": 	"78"
```
WebPack still fails with several errors like
```
ERROR in ../my_proj/node_modules/mediasoup-client/lib/handlers/Chrome70.js
Module parse failed: my_proj/node_modules/mediasoup-client/lib/handlers/Chrome70.js Unexpected token (107:12)
You may need an appropriate loader to handle this file type.
|             rtcpMuxPolicy: 'require',
|             sdpSemantics: 'unified-plan',
|             ...additionalSettings
|         }, proprietaryConstraints);
|         // Handle RTCPeerConnection connection status.
```

Specifically, it seems that it uses the "object rest spread operator" that is not yet supported widely (at least from Babel's point of view!).

For the server-side, it makes sense to use all the advanced JS features, 
but for the client-side, would it be possible to use Typescript transpilation settings that are more conservative?

Thank you for your awesome work!

**Comment by ibc** [comment]
The **Object** rest spread operator is defined in ECMAScript 2018 and we use `"target": "es2018"` in mediasoup-client so, right, they are not replaced by legacy `Object.assign()`.

Now, I don't understand the problem. Browsers do support it. What does it mean that "Babel" does not?

**Comment by ibc** [comment]
Done in mediasoup-client 3.6.14 (see https://github.com/versatica/mediasoup-client/commit/eb649d59ebc60cca0cc38abfd31d6561e6336eec)
