### ISSUE TITLE
Unrecognized WebSocket connection option(s) `origin`, `requestOptions`, `clientConfig`. Did you mean to put these under `headers`

### ISSUE THREAD

**Issue by chuanhaisoft** [versatica/mediasoup-client#131]
"mediasoup-client": "^3.6.14",
"react-native": "0.63.2",
mediasoup   3.5.7

 0.61.5 is worked well

react-native from 0.61.5 upgrade to 0.63.2,then 

 WARN     Unrecognized WebSocket connection option(s) `origin`, `requestOptions`, `clientConfig`. Did you mean to put these under `headers`

WebSocket connection failed

**Comment by ibc** [comment]
Use the forum, please.
