### ISSUE TITLE
SDP offer grows indefinitely

### ISSUE THREAD

**Issue by dimes** [versatica/mediasoup-client#132]
When the mediasoup client consumes a track, `this._handler.receive` is called. In Chrome74.ts, this action triggers `remoteSdp.receive`, which ultimately adds a media section to the remote SDP object (via `_addMediaSection`).

This media section forever becomes a part of the sdp offer, even after `remoteSdp.closeMediaSection` is called. This leads to a situation where the browser becomes unresponsive after receiving many tracks over the course of a session. I've tried clearing out the media entry from the media array in the sdp object, but chrome rejects this offer because of the order of m-lines has changed. Any guidance would be great.

**Comment by ibc** [comment]
The remote SDP does not remove m= sections of closed `Consumers` because that's how SDP works (unfortunately). There is room for improvement since we could reuse closed m= sections to allocate new `Consumers`, and we'll do it eventually.

However, what do you mean with _"the browser becomes unresponsive after receiving many tracks"_? I've never experienced that. How many m= sections has your remote SDP?

**Comment by dimes** [comment]
I'm not sure on the exact number, but it's likely thousands or tens of thousands. or millions We use one transport for consuming video in a video conference. We call consume / stop on the consumers for various reasons in the call and have found that our load testing bots become unresponsive after some time. Using the profile we find that a majority of the CPU cycles are dedicated to generating the SDP text. I guess a solution would be to add transports over time.

**Comment by ibc** [comment]
How many active consumers do you have?

Note: the solution to the issue is detailed in my previous comment. We'll handle it when we get some time.

**Comment by dimes** [comment]
There are only < 12 active consumers at any given time, but the total number of calls to consume is in the thousands after hours of use.

**Comment by dimes** [comment]
Did you mean something like this? https://github.com/versatica/mediasoup-client/pull/133

**Comment by ibc** [comment]
Released in 3.6.15

**Comment by dimes** [comment]
Thank you 🙏
