### ISSUE TITLE
consumer.getStats promise never resolves

### ISSUE THREAD

**Issue by CodingDive** [versatica/mediasoup-client#134]
Hey, thank you for this wonderful library.

We were just running into an issue where `await consumer.getStats()` is never resolved on the client. Let me know if you need any more information. I checked the demo and saw that `getStats` is only called on transports and producers. Am I doing something wrong or is it supposed to throw or resolve just like any other promise?

**Comment by ibc** [comment]
It resolves, and the demo demonstrates it:

<img width="442" alt="CleanShot-2020-09-24-at-12 04 08@2x" src="https://user-images.githubusercontent.com/16191/94131367-1de2b880-fe5e-11ea-8cf8-9c2538e74deb.png">

This si definitely not a bug in mediasoup-client. Please use the forum if you have further questions or issues.
