### ISSUE TITLE
[Android, React Native] Sound control do not work on Xiaomi phones

### ISSUE THREAD

**Issue by vadympetryshyn** [versatica/mediasoup-client#135]
When I try decrease/increase sound by clicking sound control buttons it doesn't work with mediasoup, but works great with another video or audio. Maybe problem in MIUI wrapper, I've tested on several devices with different version of Android and MIUI. 

React Native version:
0.63.0
React Native WebRTC version:
1.75.3
OS:
Android 7,8,9,10,11

**Comment by ibc** [comment]
Not related to mediasoup-client. Please ask in the react-native-webrtc project.
