### ISSUE TITLE
Video can not be produced in latest safari 14 update on Mac and iOS

### ISSUE THREAD

**Issue by saurabh-rocksoul** [versatica/mediasoup-client#138]
When I stream video and try to play it in safari on MacOS or iOS, the video won't play. If I check the capability of the browser via canProduce function it returns false.

Also, when I try to run mediasoup demo in the latest update, it also does not work.
Can something be done for this?

**Comment by ibc** [comment]
Please. Bye.

**Comment by saurabh-rocksoul** [comment]
@ibc 
?

**Comment by ibc** [comment]
Use the forum for questions. It's clearly indicated in the guidelines that you ignored above.

**Comment by saurabh-rocksoul** [comment]
I am sorry for this.
