### ISSUE TITLE
Immutable Objects Cannot Be Used as RTP Parameters

### ISSUE THREAD

**Issue by tubbo** [versatica/mediasoup-client#139]
### Your environment

- Operating system: macOS 10.15.4
- Browser version: Chrome 86.0.4240.111 
- npm version: 6.14.8
- mediasoup version: 3.6.24
- mediasoup-client version: 3.6.20

### Issue description

The objects passed to [validateRtpCodecCapability](https://github.com/versatica/mediasoup-client/blob/v3/src/ortc.ts#L64) and [validateRtpHeaderExtension](https://github.com/versatica/mediasoup-client/blob/v3/src/ortc.ts#L164) are mutated in certain cases, which means that read-only objects cannot be passed into `device.load()` as `routerRtpCapabilities`. I'm using the Apollo GraphQL client, which gives you back immutable objects, which is how I found this out. In this application, I wanted to pass the router's RTP capabilities as an object within a GraphQL query.

Here's the error I was getting:

<img width="731" alt="Screen Shot 2020-10-24 at 4 50 49 PM" src="https://user-images.githubusercontent.com/113026/97093419-c2047e80-1619-11eb-8b6f-a97510d6ba58.png"> 

The above error can be worked around by cloning each `codec` and `headerExtension` from the GraphQL response and loading it into the device that way:

```javascript
    if (routerRtpCapabilities && !device.loaded) {
      (async () => {
        let caps = { codecs: [], headerExtensions: [] }

        routerRtpCapabilities.codecs.forEach(codec => {
          caps.codecs.push({ ...codec })
        })

        routerRtpCapabilities.headerExtensions.forEach(extension => {
          caps.headerExtensions.push({ ...extension })
        })

        await device.load({ routerRtpCapabilities: caps })
      })()
    }
```

This involves a lot of "jumping through hoops" just to get a device loaded. I propose that these objects get cloned as they're used inside the validation functions described above, so that immutable objects can be passed into this function without causing errors. Also happy to make the PR if y'all are OK with the solution.

**Comment by ibc** [comment]
This is done in mediasoup-client 3.6.21.

**Comment by tubbo** [comment]
<3 thank you!
