### ISSUE TITLE
Incorrect Device detected when used inside iOS WKWebView

### ISSUE THREAD

**Issue by vpalmisano** [versatica/mediasoup-client#143]
When the web page is loaded inside a iOS WKWebView, the user agent string does not have the "Safari" string, so the Device selection made here fails:
https://github.com/versatica/mediasoup-client/blob/4693b5b80f20de9b95955a4939bc9fdd039a0548/src/Device.ts#L107

In this case, the user agent string is something like `AppleCoreMedia/1.0.0.15E217 (iPhone; U; CPU OS 11_3 like Mac OS X; en_us)`. The bowser detected object is:
```
{
  "browser": {
    "name": "AppleCoreMedia",
    "version": "1.0.0.15E217"
  },
  "os": {
    "name": "iOS",
    "version": "11.3"
  },
  "platform": {
    "type": "mobile",
    "vendor": "Apple",
    "model": "iPhone"
  },
  "engine": {}
}
```

**Comment by ibc** [comment]
Please report the issue in the [bowser](https://github.com/lancedikson/bowser) NPM library. It's unclear for me whether it should report browser name "Safari" or not in this case.

Also, I cannot test that environment so I don't know which the proper mediasoup-client handler should be for iOS WKWebView. It may be `Safari11` or `Safari12` hopefully, but I don't know.

Can you make a PR with changes in `Device.ts` to support this environment?

**Comment by vpalmisano** [comment]
No sure if this is a bowser "bug"
For now I force to use `Safari12` and it works on most devices with iOS > 11

**Comment by ibc** [comment]
> No sure if this is a bowser "bug"

Well, we need to use something like `browser.satisfies({ safari: '>=12.0' })` where instead of `safari` it would be `xxxxxxx` (I don't know), and that needs support from `bowser` library.

> For now I force to use Safari12 and it works on most devices with iOS > 11

Since the mediasoup-client API enables manual Handler selection, and since I cannot test iOS WKWebView, I'll close this issue.

**Comment by vpalmisano** [comment]
> Well, we need to use something like `browser.satisfies({ safari: '>=12.0' })` where instead of `safari` it would be `xxxxxxx` (I don't know), and that needs support from `bowser` library.

Done, issue https://github.com/lancedikson/bowser/issues/456

**Comment by ibc** [comment]
Thanks
