### ISSUE TITLE
ReplaceTrack method in React Native

### ISSUE THREAD

**Issue by vadympetryshyn** [versatica/mediasoup-client#147]
Try to use and get error "not Implemented", could you please reveal the plans about implementation of this method?

**Comment by ibc** [comment]
Ok, so you want this to work. Actually there is a good reason for this feature to not be available in React-Native: **react-native-webrtc** dependency library does NOT implement it:

https://github.com/react-native-webrtc/react-native-webrtc/search?q=replaceTrack

Please, use the mediasoup forum for future questions.
