### ISSUE TITLE
Unexpected changes maxSpatialLayer in the other producers

### ISSUE THREAD

**Issue by geongun20** [versatica/mediasoup-client#153]
### Your environment

- Operating system: OS X Catalina 10.15.7
- Browser version: google chrome 87.0.4280.141
- npm version: 6.14.4
- mediasoup version: 3.6.30
- mediasoup-client version: 3.6.12

### Issue description

1. produce video track with under encodings.
```typescript
const SIMULCAST_ENCODINGS = [
  {
    rid: 'q',
    scaleResolutionDownBy: 4.0,
    scalabilityMode: 'L1T3',
    maxBitrate: 100000, // 100k
  },
  {
    rid: 'f',
    scalabilityMode: 'L1T3',
    maxBitrate: 1700000, // 1700k
  },
]; 
```
2. setMaxSpatialLayer to 0 on the created producer
3. produce audio track
4. then maxSpatialLayer of video producer is 0 but, bitrate of video producer is 1700000

**Comment by ibc** [comment]
Please report to libwebrtc. Not a bug in mediasoup-client.
