### ISSUE TITLE
Can't produce/consume stream from android (react-native)

### ISSUE THREAD

**Issue by iamvucms** [versatica/mediasoup-client#158]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup-client.

If you have questions or doubts about mediasoup-client or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

### Your environment

- Operating system: React Native and Chrome
- Browser version:
- npm version:6.14.10
- mediasoup version: 3.6.32
- mediasoup-client version: 3.6.28

### Issue description
```
producerTransport.on('connectionstatechange', (state) => {
          switch (state) {
            case 'connecting':
              console.log('publishing...');
              break;
            case 'connected':
              console.log('published');
              break;

            case 'failed':
              console.log('failed');
              producerTransport.close();
              break;
            default:
              break;
          }
        });

consumerTransport.on('connectionstatechange', (state) => {
            switch (state) {
              case 'connecting':
                console.log('subscribing...');
                break;

              case 'connected':
                console.log('subscribed');
                //consumeCurrentProducers(clientId);
                break;

              case 'failed':
                console.log('failed');
                producerTransport.close();
                break;

              default:
                break;
            }
          });
```
**Android** always show **failed** when produce/consume stream.
**IOS** is working fine, can produce video and consume stream. 
Hope anyone can help me out this issue.

**Comment by ibc** [comment]
Use the forum for usage questions/problems.
