### ISSUE TITLE
Typescript - Error in lib/types.d.ts

### ISSUE THREAD

**Issue by manfredxu99** [versatica/mediasoup-client#162]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup-client.

If you have questions or doubts about mediasoup-client or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

### Your environment

- Operating system: macOS Big Sur 11.2.3
- Browser version: Chrome 89.0.4389.90
- npm version: 6.11.3
- mediasoup version: 
- mediasoup-client version: 3.6.29

### Issue description

Getting a syntax error in types.d.ts, the export type is causing an error in typescript and I'm required to manually edit this file each time

```
node_modules/mediasoup-client/lib/types.d.ts(11,1):
Declaration or statement expected.  TS1128

     9 | export * from './handlers/HandlerInterface';
    10 | export * from './errors';
  > 11 | export type { ScalabilityMode } from './scalabilityModes';
```

**Comment by ibc** [comment]
Just use TypeScript >= 3.8.
