### ISSUE TITLE
Cannot decode H264 while one can only encode VP8

### ISSUE THREAD

**Issue by scaret** [versatica/mediasoup-client#163]
https://github.com/versatica/mediasoup-client/blob/v3/src/Transport.ts#L591

The function canReceive depends on Transport._extendedRtpCapabilities, and _extendedRtpCapabilities depends on whether the device can encode with the codec.

So if Browser A can decode H264 but can only encode VP8, Transport._extendedRtpCapabilities will not contain H264. So if Browser B can only encode H264, mediasoup will reject A receiving from B. If I comment the line, the browse will accept the sdp and works fine.

**Comment by ibc** [comment]
I'm afraid we are not ready for having different encoding & decoding capabilities. Perhaps in the future.

**Comment by ibc** [comment]
Closing this issue in favour of #141.
