### ISSUE TITLE
Cannot find name 'RTCPriorityType'.

### ISSUE THREAD

**Issue by sinclairzx81** [versatica/mediasoup-client#167]
### Your environment

- Operating system: Ubuntu 20.x
- Browser version: Chrome
- npm version: 7.16.0
- mediasoup version: 3.7.12
- mediasoup-client version: 3.6.30
- TypeScript: 4.3.2

### Issue description

Seem to be missing the `RTCPriorityType` on the `mediasoup-client` when compiling with TypeScript `4.3.2`. This causes TypeScript to fail to build with the following. 

```bash
node_modules/mediasoup-client/lib/DataProducer.d.ts:7:16 - error TS2304: Cannot find name 'RTCPriorityType'.

7     priority?: RTCPriorityType;
                 ~~~~~~~~~~~~~~~

node_modules/mediasoup-client/lib/SctpParameters.d.ts:62:16 - error TS2304: Cannot find name 'RTCPriorityType'.

62     priority?: RTCPriorityType;
                  ~~~~~~~~~~~~~~~
Found 2 errors.
```
The `RTCPriorityType` may have been culled in `typescript@4.3.2` (there is mention to the TS team culling a bunch of types in this release). Compiling with `typescript@4.2.4` resolves the problem.

**Comment by ibc** [comment]
Fix released in 3.6.31

**Comment by sinclairzx81** [comment]
Brilliant, thank you!

**Comment by iamarkdev** [comment]
@ibc  RTCPriorityType seems to be missing in the latest mediasoup-client package and there is no typings available to set the priority of a dataproducer although the docs state it as an option here: https://mediasoup.org/documentation/v3/mediasoup-client/api/#DataProducerOptions

**Comment by ibc** [comment]
> [@ibc](https://github.com/ibc) RTCPriorityType seems to be missing in the latest mediasoup-client package and there is no typings available to set the priority of a dataproducer although the docs state it as an option here: https://mediasoup.org/documentation/v3/mediasoup-client/api/#DataProducerOptions

Ok, I've removed `priority` from `DataProducerOptions` in the docs.
No, it's not missing. Setting the DataChannel priority was removed from the WebRTC spec many years ago. It's not a real thing anymore.
