### ISSUE TITLE
Release 3.6.29 breaks rollup

### ISSUE THREAD

**Issue by asjur** [versatica/mediasoup-client#168]
### Your environment

- Operating system: Archlinux
- Browser version: Firefox 89
- npm version: 7.15.1
- mediasoup version: not relevant
- mediasoup-client version: 3.6.29

### Issue description
I am developing a video conferencing solution using Svelte which uses Rollup. Mediasoup-client requires `preferBuiltins` to be set to `false` to function, that is fine. However the last working version for users who need Rollup is 3.6.28, in 3.6.29 and to current version mediasoup-client will cause an error that "exports is not defined" in `lib/RtpParameters.js`

[I believe this is the offending commit](https://github.com/versatica/mediasoup-client/commit/8dafce002adc6173815b52d0ac9e0618278761fe)

My tsconfig extends svelte's provided tsconfig which already has the necessary options set:
`"esModuleInterop": true,` and `"isolatedModules": true,`

**Comment by ibc** [comment]
I have no idea about Rollup so I need more context and also which change you are proposing in mediasoup-client (without breaking others).

**Comment by asjur** [comment]
Sadly I do not know what it required to fix it. I just know that rollup is used by quite a few projects and is default for the Svelte "framework". 

Considering I don't have the knowledge to really know what's causing this I resorted to switching my svelte project over to webpack and that does work. Hopefully someone with a bit more knowledge of rollup can shed some light on why it breaks.

**Comment by cheluskin** [comment]
"mediasoup-client": "^3.6.33", and not troubles with build. 
Try it. This can help

`replace({
			'Object.defineProperty(exports, "__esModule", { value: true });': '',
			delimiters: ['\n', '\n'],
			preventAssignment: true
		  }),`

**Comment by ibc** [comment]
TypeScript >= 3.8 is required by mediasoup-client. I'm afraid we cannot support frameworks that rely on older TypeScript versions.

**Comment by asjur** [comment]
Not sure where you got that the framework doesn't support typescript 3.8?

**Comment by ibc** [comment]
I'm afraid no info has been given in this issue and I'm not gonna become a Rollup expert to investigate it. Anyway it's related to TypeScript version for sure.
