### ISSUE TITLE
Can not use for angular project

### ISSUE THREAD

**Issue by thanhkhanhcntt** [versatica/mediasoup-client#169]
Angular version 7, typescript 3.8, can not build project when import from 'mediasoup-client'

ERROR in node_modules/mediasoup-client/lib/types.d.ts:11:1 - error TS1128: Declaration or statement expected.

11 export type { ScalabilityMode } from './scalabilityModes';
   ~~~~~~
node_modules/mediasoup-client/lib/types.d.ts:11:13 - error TS1005: ';' expected.

11 export type { ScalabilityMode } from './scalabilityModes';
               ~
node_modules/mediasoup-client/lib/types.d.ts:11:38 - error TS1005: ';' expected.

11 export type { ScalabilityMode } from './scalabilityModes';
                                        ~~~~~~~~~~~~~~~~~~~~

    
    ERROR in node_modules/mediasoup-client/lib/types.d.ts:11:8 - error TS2304: Cannot find name 'type'.
    
    11 export type { ScalabilityMode } from './scalabilityModes';
              ~~~~
    node_modules/mediasoup-client/lib/types.d.ts:11:15 - error TS2304: Cannot find name 'ScalabilityMode'.
    
    11 export type { ScalabilityMode } from './scalabilityModes';
                     ~~~~~~~~~~~~~~~
    node_modules/mediasoup-client/lib/types.d.ts:11:33 - error TS2304: Cannot find name 'from'.
    
    11 export type { ScalabilityMode } from './scalabilityModes';

**Comment by ibc** [comment]
We cannot satisfy all Angular versions. You need to upgrade it, sorry.
