### ISSUE TITLE
Support mediasoup-client to run in nodejs command line environment

### ISSUE THREAD

**Issue by chenzx** [versatica/mediasoup-client#176]
I'm building a nodejs test client script to do RTP push, but surprised to find that mediasoup-client only support browser env, i tried to use server-side mediasoup lib, but it has no `Device` class...

**Comment by chenzx** [comment]
wait, i just found mediasoup nodejs client needs [mediasoup-client-aiortc](https://github.com/versatica/mediasoup-client-aiortc/blob/v3/README.md) to run, why not use server-side mediasoup lib?

**Comment by ibc** [comment]
Questions in the forum, please.
