### ISSUE TITLE
react native handler._sendStream memory leak

### ISSUE THREAD

**Issue by richmonkey** [versatica/mediasoup-client#177]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup-client.

If you have questions or doubts about mediasoup-client or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

### Your environment

- Operating system:
- Browser version:
- npm version:
- mediasoup version:
- mediasoup-client version:v3

### Issue description
https://github.com/versatica/mediasoup-client/blob/v3/src/handlers/ReactNative.ts

close(): void
	{
		logger.debug('close()');

               //free memory,  native dispose stream&track
                _sendStream.release();
		// Close RTCPeerConnection.
		if (this._pc)
		{
			try { this._pc.close(); }
			catch (error) {}
		}
	}

**Comment by ibc** [comment]
Thanks. Done in 3.6.37.

**Comment by ibc** [comment]
I'm removing b70b9b5 as explained in this commit: https://github.com/versatica/mediasoup-client/commit/b0ce063b395fa432ade69660bca11b626cf9d45c

It's parent's responsibility to release individual tracks given to `sendTransport.produce()`. The mediasoup-client `ReactNative` handler should not release them for many reasons:

1. Because if a track is added, then removed, we were not calling `release()` on it so here there was a leak.
2. Because the parent (the app) may still want to use the audio or video local track even after the mediasoup-client `Producer` was closed.

**Comment by ibc** [comment]
Removed in 3.6.38

**Comment by richmonkey** [comment]
Yes,  I agree, track's owner is app.
but need this._sendStream.release(false).

Another problem when app release track?
 when app close producer, on producer close event app can't release track, because stopSending may be in pending queue, very little possability.

producer.on("close", () => {
   //timeout wait stopSending completed
   setTimeout(()=> {
      track.release();
    }, 100);
})

**Comment by ibc** [comment]
> Yes, I agree, track's owner is app.
> but need this._sendStream.release(false).

Right. Done in 3.6.39.



> Another problem when app release track?
> when app close producer, on producer close event app can't release track, because stopSending may be in pending queue, very little possability.

App must release track when it no longer needs it for anything. Once it closes the Producer or the sendTransport, mediasoup-client is not gonna try to use it at all.

**Comment by richmonkey** [comment]
Let's assume producer closed, track no longer needs.
producer.on("close", () => {
    //can't release here, because after producer close event,
   // mediasoup client maybe still use the track in transport _awaitQueue
    track.release();  //bad
    
   //timeout wait stopSending completed is more robust.
   setTimeout(()=> {
       track.release();
    }, 100);   //ok

})

**Comment by richmonkey** [comment]
https://github.com/versatica/mediasoup-client/blob/v3/src/Transport.ts   lineno:834

**Comment by ibc** [comment]
Such a line calls `async () => this._handler.stopSending(producer.localId)` which will just remove the track from the PeerConnection. It should not crash anything.

**Comment by richmonkey** [comment]
If track.release before this._handler.stopSending(producer.localId),
the track won't be removed from steam.

so when  native mediastream dispose will also dispose the track in the stream, then app will crash at 
https://chromium.googlesource.com/external/webrtc/+/master/sdk/android/api/org/webrtc/MediaStreamTrack.java
function: checkMediaStreamTrackExists
lineno: 120

**Comment by ibc** [comment]
So react-native-webrtc is a disaster which assumes that local tracks must be totally managed by the PeerConnection. I hate it.

**Comment by ibc** [comment]
> so when native mediastream dispose will also dispose the track in the stream, then app will crash at

No because ReactNative.close() now calls to this: `this._sendStream.release(/* releaseTracks */ false);`

right?

**Comment by richmonkey** [comment]
First: react native webrtc  track.release will call native mediastreamtrack.dispose

Second:this._sendStream.release(false) will call native webrtc mediastream.dispose
https://chromium.googlesource.com/external/webrtc/+/master/sdk/android/api/org/webrtc/MediaStream.java  lineno:75
It will dispose the tracks, but  tracks can't dispose twice.

So native mediastreamtrack  dispose must after removed from native mediastream.

The right progress
_handler.stopSending(producer.localId) , result is native mediastreamtrack removed from native mediastream
then native mediastreamtrack.dispose (js  track.release)

**Comment by richmonkey** [comment]
I prefer native webrtc to react-native-webrtc on ios&android.
I like to write jni&object-c binding for libmediasoupclient, but i do not like some interface of libmediasoupclient.
Off course I like mediasoup very much. The mediasoup design&code is great.

**Comment by ibc** [comment]
May I please know what you suggest? Is it the stream.release(false) in close() method ok? Should the parent app take care of when to call track.release()?

**Comment by richmonkey** [comment]
1. stream.release(false) in close is ok.
2. Should the parent app take care of when to call track.release() yes
   detail:  when producer closed, delay 100ms to close the track

**Comment by ibc** [comment]
Thanks a lot. Let's close the issue again :)

**Comment by ibc** [comment]
News here after a week dealing with a crash in Android:

https://github.com/versatica/mediasoup-client/commit/2b6c0f461575247a5b2ba9bf34fd805bed1d2854

**Comment by richmonkey** [comment]
react native webrtc  RTCPeerConnection close won't release the localstream.
react native webrtc crash may be related:
https://github.com/react-native-webrtc/react-native-webrtc/issues/1062#issuecomment-915146083

**Comment by ibc** [comment]
Excellent catch. We'll update the code once there is a new version of react-native-webrtc.

**Comment by ibc** [comment]
FYI @richmonkey: 3586e7ba29260b659a3a0239d1f7634ddbc98d23

Released in mediasoup-client 3.6.41
