### ISSUE TITLE
The type of binaryType field in DataConsumer mismatches the type of the underlying field in the latest typescript

### ISSUE THREAD

**Issue by snnz** [versatica/mediasoup-client#179]
### Your environment

- mediasoup-client version: 3.6.37

### Issue description

The type of the `binaryType` field of the `RTCDataChannel` interface was recently changed to `BinaryType` in the typescript. So compilation with the latest tsc fails with the following error:

`src/DataConsumer.ts:141:3 - error TS2322: Type 'string' is not assignable to type 'BinaryType'.`
`141   this._dataChannel.binaryType = binaryType;`

Suggestion: update dependences to the latest typescript and change the type of the `binaryType` getter and setter in DataConsumer to `BinaryType`.

**Comment by ibc** [comment]
Fixed in 3.6.46
