### ISSUE TITLE
Expose functionality to update encodings in device handlers

### ISSUE THREAD

**Issue by hkirat** [versatica/mediasoup-client#182]
## Feature Request
We have a use-case where we want to dynamically change the encodings on a transceiver.
Specifically a change that looks like this - 

Change from 
```
encodings: [
  {
     maxBitrate: 100000
  },
  {
     maxBitrate: 200000
  },
]
```

to 

```
encodings: [
  {
     maxBitrate: 50000
  },
  {
     maxBitrate: 140000
  },
]
```

The device handlers do expose `setRtpEncodingParameters` but they change a property to the same value on all the encodings.

It would be nice to have a `updateEncodingParameters` that lets us update each encoding individually.

This might already be a thing somewhere in the mediasoup-client, and if it is I apologise for filing a dupe feature request.

If this isn't already there, I'd be happy to file for a PR if the authors agree with the feature request proposal.

**Comment by ibc** [comment]
Use producer.sender.
