### ISSUE TITLE
Change DTLS role of send transports from "server" to "client"

### ISSUE THREAD

**Issue by jbaudanza** [versatica/mediasoup-client#183]
## Feature Request

Currently,  send transports take the role of the DTLS server on mediasoup-client. This is causing difficulties on some networks while running in a dual-stack (ipv4 + ipv6) configuration. Taking the role of "client" seems to be a lot more reliable.

Here are the details from my original forum post (https://mediasoup.discourse.group/t/dtls-roles-on-dual-stack-ipv4-ipv6-server/3529)

I'm running Mediasoup and binding to both IPv4 and IPv6 addresses. All of my users are on mobile devices.

Everything works fine for the vast majority of users. But there are some users on "weird" networks that have a problem finishing the DLTS handshake on send transports.

As an example of weird network:
  1. Put your iPhone into hotspot mode, and connect another device via Wifi to your hotspot
  2. Try to connect using libwebrtc from the iPhone (not the connected device)
  3. The send transport won't get past the DTLS handshake, but recv transports work just fine.

This use case is rare, but I think it's valid and I'd like to support it.

I've also had this same problem with users behind some sort of IPv6/IPv4 NAT, as described here: https://mediasoup.discourse.group/t/client-on-ipv6-nat-can-only-complete-ice-with-send-transports/2702/8

The problem with these "weird" networks it that they have two possible routes to send packets (ipv4 + ipv6), but only one possible route to receive packets (ipv4 OR ipv6, depending on the network).

If libwebrtc tries to connect DTLS from a client role over the bad route, it quickly gives up and switches to the good route.

If libwebrtc tries to connect DTLS from a server role over the bad route, it waits forever for dtls message from the mediasoup server, which never comes.

I am able to resolve this by changing send transports to use the same DTLS roles as recv transports. I do this by changing this line in mediasoup-client from "server" to "client".
https://github.com/versatica/mediasoup-client/blob/db4cbb6970b7409947a398c3db47aad291e25ce1/lib/handlers/ReactNative.js#L205

For this feature request, I'd like to suggest one of these solutions:

1. Switch all the transports in mediasoup-client to use the "client" role. Is there a reason for the difference? I've dug through the code, and I can't see anything. Please let me know if I've missed something.
2. If 1 isn't possible, can we let the DTLS role selection to be configured through the API somehow?

Thank you!

Also, I'm happy to prepare a PR.

**Comment by ibc** [comment]
This is implemented in medisoup-client 3.6.44, see rationale in the announcement: https://mediasoup.discourse.group/t/medisoup-client-3-6-44-released-with-ability-to-force-local-dtls-role/3571
