### ISSUE TITLE
NativeScript Handler

### ISSUE THREAD

**Issue by countradooku** [versatica/mediasoup-client#187]
## Feature Request
Can you make a NativeScript handler?
You can use this maybe
https://www.npmjs.com/package/nativescript-webrtc-plugin
i wanna make an webrtc app using mediasoup and nativescript

**Comment by ibc** [comment]
I'm afraid we don't have time to investigate it and won't make such an effort. I don't even know what NativeScript is, and the lib you referenced is 2 years old so obviously amateur and unmaintained.
