### ISSUE TITLE
Device Not Supported error in Instagram Browser when initializing Device

### ISSUE THREAD

**Issue by oveddan** [versatica/mediasoup-client#188]
This occurs with mediasoup-client version 3.6.47

Sometimes, our users have links our web application on their instagram page; our web application heavily uses `mediasoup-client`. When trying to initialize the mediasoup client device, with:

```js
import { Device } from 'mediasoup-client';
new Device();
```

On the Instagram browser on the iphone, you get an error:
 UnsupportedError: device not supported

This does not occur on ios safari on chrome.

I've built and deployed a minimal application that demonstrates this:

The code looks like:
```js
import { Device } from 'mediasoup-client';

const deviceDebug = document.getElementsByTagName('h2')[0];
const browserDebug = document.getElementsByTagName('p')[0];

if (typeof navigator === 'object' && navigator.product === 'ReactNative')
{
  browserDebug.innerText = 'device: ReactNative';
} else {
  browserDebug.innerText = `user agent: ${navigator.userAgent}`;
}

try {
  new Device();

  deviceDebug.innerText = 'succeeded loading device.';
} catch(e) {
  deviceDebug.innerText = e.toString();
}
```

With corresponding html:
```
<!doctype html>
<html lang="en">
  <body>
    <h1>Loading mediasoup device....</h1>
    <p></p>
    <h2></h2>
  </body>
  <script type="module" src="app.js"></script>
</html>
```

And the full code example can be found here:
https://github.com/oveddan/device-not-supported-demo/blob/master/src/app.js

It is currently deployed to:
https://device-not-supported-demo.netlify.app/

And you can try accessing this site thru the instagram browser by opening the instagram profile (in the instagram app):
myrtl_e9995 (at instagram.com/myrtl_e9995)

When opening that url thru the instagram link, this is what shows up:
![IMG_4958](https://user-images.githubusercontent.com/891755/144943708-e2940025-e03e-42d2-8fad-d2bf4b6fb583.jpg)

**Comment by ibc** [comment]
We cannot support all fancy browsers that are just embedded Safari or Chrome. Check the Device constructor options.
