### ISSUE TITLE
Edge consumers are not working

### ISSUE THREAD

**Issue by Demivan** [versatica/mediasoup-client#19]
There are multiple issues with Edge transport for consumers:
1. `_setupTransport` is not called when calling `addConsumer`
2. `MediaStreamTrack` is not returned from `addConsumer` method

**Comment by Demivan** [comment]
I can create pull request with fixes

**Comment by ibc** [comment]
Yes please, report the exact issues or make a PR. Unfortunately we won't be able to check Edge for a while.

**Comment by Demivan** [comment]
These are exact issues :)
Pull request created
