### ISSUE TITLE
Does it support h265 video encoding？

### ISSUE THREAD

**Issue by XianWang-Lu** [versatica/mediasoup-client#190]
1. Searching in source code,The phrase "h265" appeared once and the phrase "hevc' not found.It's so different to the phrase "vp8"/"vp9" and "h264" which appeared many times.
2. I use a browser supported h265 named "科达浏览器",but the codec.mimeType of RtpCodecCapability getted by mediasoup-client from browser is "video/HEVC",not "video/h265".On the server,when I modify the value "video/VP9" to "video/HEVC" in config.js,it throws "Not Supported" error.
 It seems to support h265 video encoding, but I can't find how to implement it.So if it supports h265 video encoding?

**Comment by ibc** [comment]
Questions in the mediasoup forum, please.
