### ISSUE TITLE
Firefox issue when the first m= becomes inactive

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client#2]
No idea how to handle this: https://bugzilla.mozilla.org/show_bug.cgi?id=1393407

Something coming to my mind is:

* If `removeProducer` or `removeConsumer` is called, and it corresponds to the first `m=` section, abort.

### Related:

* [Firefox attempts to establish a new ICE+DTLS transport when moving from 0 local tracks to N](https://bugzilla.mozilla.org/show_bug.cgi?id=1355486)
* [PeerConnection stops functioning properly after receiving disabled m= line in SDP without a=inactive attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1370562)
* [Chrome rejects remote answer that tries to change a previously selected BUNDLE-tag](https://bugs.chromium.org/p/webrtc/issues/detail?id=6704)

**Comment by ibc** [comment]
A better solution could be, when in a sending peerconnection, adding a fake receiving audio track in the "remote" SDP answer. And, when in a receiving peerconnection, adding a fake sending audio track (generated somehow...).

**Comment by jmillan** [comment]
I think your last approach is the best one; attaching a fake audio track which will not be removed during the life of the RTCPeerconnection, holding this way the transport definition (until FF fixes the bug)

**Comment by ibc** [comment]
Right. In fact, the issue does not just happen when removing the latest active track, but when the first m= section becomes inactive. This is, in a simple audio+video sendonly PeerConnection in Firefox, if the audio track (mic) is closed, the ICE is closed (so video is not transmitted anymore).

Yes, we need to add a fake first m=audio section. NOTE: This is easy in the recvonly pc, but not so easy in the sendonly pc.

**Comment by ibc** [comment]
OK, f0e81ca fixes the receiving PeerConnection of Firefox by adding a fake DataChannel as the first m= section in the remote SDP offer, so the first m= section is always active and Firefox does not close the ICE+DTLS if there are no remote tracks.

The sending PeerConnection is not yet fixed so, for now, the first added Producer (typically the mic audio) should never be closed.

**Comment by ibc** [comment]
The sending issue is fixed in Firefox 57: https://bugzilla.mozilla.org/show_bug.cgi?id=1393407

The received one is also supposed to be fixed in Nightly, but I cannot confirm because it crashes. However the DataChannel hack was already a valid work around, so closing this issue.
