### ISSUE TITLE
Getting Error on Creating the Device object in React Naitve

### ISSUE THREAD

**Issue by avigator003** [versatica/mediasoup-client#202]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup-client.

If you have questions or doubts about mediasoup-client or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

### Your environment

- Operating system: macOS BigSur M1
- Browser version: React Native with expo
- npm version:  8.3.1
- mediasoup version: 3.9.7 
- mediasoup-client version: 3.6.50
- react-native-webrtc: github:openland/react-native-webrtc#master

### Issue description
TypeError: null is not an object (evaluating 'WebRTCModule.mediaStreamCreate') Getting this error when I  try to create a device object.
```js
 const handlerName = mediasoup.detectDevice()
 const device = new mediasoup.Device({ handlerName})
 ```
 I have taken all the permissions like camera,audio etc. before creating the device object.

**Comment by ibc** [comment]
Please, usage issues in the public forum, not here.
