### ISSUE TITLE
Firefox 96+ version dont send video stream

### ISSUE THREAD

**Issue by mpbikc** [versatica/mediasoup-client#205]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup-client.

If you have questions or doubts about mediasoup-client or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

### Your environment

- Operating system: Windosw
- Browser version: Firefox 96+
- npm version:  6.14.10
- mediasoup version: 3.9.10
- mediasoup-client version: 3.6.51

### Issue description
After Firefox New version in January(96 version) where they changed webrtc engine we can't send video stream to mediasoup.
Audio works fine. 
On previous version both video and audio works fine.
Another browsers works fine

In BBB issue tracker we can find assotiated and fixed bug https://github.com/bigbluebutton/bigbluebutton/issues/14066
Where they describe the reason of that bug.
I think it should be fixed in main mediasoup-client

**Comment by mpbikc** [comment]
codecs for Router:

var mediaCodecs =
        [
            {
                kind: 'audio',
                mimeType: 'audio/opus',
                clockRate: 48000,
                channels: 2
            },                       
            {   
                kind: "video",
                mimeType: "video/H264",
                clockRate: 90000,
                parameters:
                {
                    "packetization-mode": 1,
                    "profile-level-id": "42e01f",
                    "level-asymmetry-allowed": 1
                }
            }
        ];

**Comment by ibc** [comment]
Use the for usage questions or problems. This is not a bug. Nobody said that Firefox allows all H264 codec configurations. Please do not comment here but in the pubic forum.
