### ISSUE TITLE
Producer: use `a=inactive` to keep the original track yet avoid sending RTP

### ISSUE THREAD

**Issue by jmillan** [versatica/mediasoup-client#213]
## Feature Request

We don't have this feature and it's needed to avoid sending RTP while keeping the MediaStreamTrack set.

Removing and re-adding the track to the transceiver will create lip sync when pausing/resuming repeteadly.

WIP: https://github.com/versatica/mediasoup-client/tree/producer-transceiver-inactive-on-pause

**Comment by ibc** [comment]
This was done long ago.
