### ISSUE TITLE
Use Progressive Enhancement/"Mustard cutting" rather than UA sniffing to determine feature support

### ISSUE THREAD

**Issue by barlock** [versatica/mediasoup-client#218]
## Feature Request

User agent strings are [notorious](https://webaim.org/blog/user-agent-string-history/) for being deceptive and change frequently. 

Because of this it's better practice to use feature detection combined with progressive enhancement on your environment to enable/disable features.

Handlers are being selected based on UA sniffing, the cost of this is that it forces project authors to duplicate a bunch of code making it harder to maintain _and_ not supporting devices which are perfectly cable of running mediasoup client (Eg: #189).

**Comment by barlock** [comment]
And I'd be happy to work on this, but it would be a fairly large departure from the current architecture of agent handlers so I wanted to check it would be an acceptable change first.

**Comment by ibc** [comment]
Users can already skip UA based built-in handler selection and pass it manually via  `DeviceOptions`:

- https://mediasoup.org/documentation/v3/mediasoup-client/api/#device-new-Device
- https://mediasoup.org/documentation/v3/mediasoup-client/api/#DeviceOptions

UA based choice is just a best effort.

**Comment by ibc** [comment]
Once WebRTC capable browsers converge into the final spec we may remove those handlers and do something different, but for now we prefer to keep it this way.
