### ISSUE TITLE
Support react-native-webrtc  version 1.106 +

### ISSUE THREAD

**Issue by guoqikai** [versatica/mediasoup-client#221]
React-native-webrtc recently switched to the unified plan: https://github.com/react-native-webrtc/react-native-webrtc/releases The current handler just won't work with the new version.

**Comment by ibc** [comment]
We are aware. Will be done when we get some time.

**Comment by ibc** [comment]
Looking for testers: https://mediasoup.discourse.group/t/need-testers-for-reactnative-unified-plan/4739

**Comment by ibc** [comment]
PR with Unified Plan support done and needs testing: https://github.com/versatica/mediasoup-client/pull/228

**Comment by guoqikai** [comment]
> Looking for testers: https://mediasoup.discourse.group/t/need-testers-for-reactnative-unified-plan/4739

Thanks for the update! We are working on testing these new changes on our mobile devices. I'll let you know if we spot any issues with the new release.

**Comment by ibc** [comment]
> I'll let you know if we spot any issues with the new release.

Actually I'd prefer if you can also confirm that it works fine even if there are no issues.

**Comment by guoqikai** [comment]
> > I'll let you know if we spot any issues with the new release.
> 
> Actually I'd prefer if you can also confirm that it works fine even if there are no issues.

Did few tests yesterday and seems like it works fine for our use cases, which includes creating video/audio producer, and creating/updating video/audio consumer with simulcast enabled. We don't use the data channel.

Haven't tested anything around the replaceTrack/zeroRtpOnPause area(which I think it supposed to be the 'new features') yet but I think we might need to utilize these features to fix some workaround in the near future so I'll keep you updated on how that goes.

Thanks again for fixing our issue!

**Comment by ibc** [comment]
Thanks a lot @guoqikai
