### ISSUE TITLE
3.6.61 incorrectly moved debug from dependency to dev dependency

### ISSUE THREAD

**Issue by ebroder** [versatica/mediasoup-client#224]
### Your environment

- Operating system: Linux
- Browser version: N/A
- npm version:
- mediasoup version:
- mediasoup-client version: 3.6.61

### Issue description

It looks like 769e1d82eee7a0178962ecc4648a623fa66dc5ff moved the `debug` package from being a dependency to being a dev dependency. However, (non-test file) `src/index.ts` still imports `debug`: https://github.com/versatica/mediasoup-client/blob/5a4f792873905b88820d50cfea153207c0d06c82/src/index.ts#L1

This is a [build failure](https://github.com/deathandmayhem/jolly-roger/actions/runs/3515562550/jobs/5892600954) in my project:

```
node_modules/mediasoup-client/lib/index.d.ts(1,19): error TS7016: Could not find a declaration file for module 'debug'. '/home/runner/work/jolly-roger/jolly-roger/node_modules/mediasoup-client/node_modules/debug/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/debug` if it exists or add a new declaration (.d.ts) file containing `declare module 'debug';`
```

**Comment by ibc** [comment]
Thanks. Fixed in 3.6.62.
