### ISSUE TITLE
_recvTransport connect  no callback，but _sendTransport is have

### ISSUE THREAD

**Issue by jackwxs** [versatica/mediasoup-client#225]
if(_consume){
        const transportInfos = await _protoo.request('createWebRtcTransport',
            {
                forceTcp         : false,
                producing        : false,
                consuming        : true
            });

        const {
            id,
            iceParameters,
            iceCandidates,
            dtlsParameters,
            sctpParameters
        } = transportInfos;

      
        _recvTransport = _mediasoupDevice.createRecvTransport({
                        id,
            iceParameters,
            iceCandidates,
            dtlsParameters :
            {
                ...dtlsParameters,
                role : 'auto'
            },
            sctpParameters
        });
    
        _recvTransport.on('connect', async ({ dtlsParameter }, callback, errback) => 
        {
                await _protoo.request('connectWebRtcTransport',{
                    transportId : _recvTransport.id,
                    dtlsParameter
                })
                .then(callback)
                .catch(errback);
         });
    }

**Comment by jackwxs** [comment]
Using libmediasoup is fine，but JavaScript sdk doesn't work

**Comment by jackwxs** [comment]
Not helpful at all




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "versatica/mediasoup-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [versatica/mediasoup-client] _recvTransport connect  no callback，but _sendTransport is have (Issue #225)





 
Closed #225 as completed.

**Comment by ibc** [comment]
Of course not. Bye.
