### ISSUE TITLE
rtpSender.replaceTrack support in Chrome 65

### ISSUE THREAD

**Issue by thehappycoder** [versatica/mediasoup-client#23]
https://github.com/versatica/mediasoup-client/commit/4ed79488d3dff2288632ad36003829bf31be6126#diff-baa1c0fc131ac17847da1f8864df2863

> Add Chrome67 handler with support for rtpSender.replaceTrack()

Isn't Chrome 65 already supporting it? https://www.chromestatus.com/features/5700232381726720

**Comment by ibc** [comment]
AFAIK it waa buggy in M65 (read the issue in the Chromium tracker). I've just tested in Canary M67 and it works fine. 

P.S. Please, let's use the mailing list for discussions.
