### ISSUE TITLE
Missing observer event on DataConsumer/DataProducer

### ISSUE THREAD

**Issue by havfo** [versatica/mediasoup-client#230]
### Your environment

- Operating system: Debian Sid
- Browser version: Firefox 107.0
- npm version: 8.19.2
- mediasoup version: 3.11.3
- mediasoup-client version: 3.6.63

### Issue description
This issue is the same for both DataConsumer and DataProducer, so I will give the example in the DataConsumer.

If the internal datachannel object fires off the `close` event, that will internally be handled as a close of the DataConsumer, but it does not fire the observer `close` event in that case.
https://github.com/versatica/mediasoup-client/blob/7710c0a0c362b0e0d35167aa9185474bc2797f1a/src/DataConsumer.ts#L260

**Comment by ibc** [comment]
Fixed in 3.6.64, thanks.
