### ISSUE TITLE
Unable to send video from iOS when using the latest version of react-native-webrtc, which only supports Unified Plan.

### ISSUE THREAD

**Issue by filipi87** [versatica/mediasoup-client#251]
### Your environment

- React Native: 0.70.5
- react-native-webrtc: Tested using the latest tag 106.0.6
- mediasoup-client version: 3.6.80
- Tested with both:
  - iOS 15.7.3 (iphone 6s)
  - iOS 16.3 (iphone 14 pro)

Receiver side:
- Operating system: Mac M1
- Browser version: chrome 107.0.5304.110
- npm version: v16.19.1
- mediasoup-client version: 3.6.80

### Issue description

Unable to send video from iOS when using the latest version of `react-native-webrtc`, `106.0.6`, which only supports Unified Plan.

The issue **only happens** if we are using **encodings**, otherwise It works fine.

The encodings which I am using:
```
[
   {
      "active":true,
      "maxBitrate":200000,
      "maxFramerate":10,
      "scaleResolutionDownBy":4
   },
   {
      "active":true,
      "maxBitrate":680000,
      "maxFramerate":30,
      "scaleResolutionDownBy":1
   }
]
```

I was able to make It work, if I change the ReactNativeUnifiedPlan handler to behave in a similar way as the [Safari12 handler](https://github.com/versatica/mediasoup-client/blob/8f80c6a853bba2801f102c9d8d276a08aa8ad297/src/handlers/Safari12.ts#L292) to send the video.

More details about the change in this commit: https://github.com/daily-co/mediasoup-client/pull/2/commits/598bdfda3cc58021add0b983623e43baee9c33e7

If you think this change makes sense, I can open a PR with the fix.

**Comment by ibc** [comment]
Basically you are enabling old fashion simulcast for a libwebrtc version that is supposed to support the new/standard way. What error do you get in logs other than "there is no video"?

**Comment by filipi87** [comment]
Hi @ibc , I am not receiving any errors on log, that is why I have not shared them. But follow the logs from both sides:
- iOS: which I am using to send the video.
- Chrome: to receive

I have also attached the SDP offer and answer from chrome.

[log_sender_ios.txt](https://github.com/versatica/mediasoup-client/files/10860750/log_sender_ios.txt)
[log_receiver_chrome.txt](https://github.com/versatica/mediasoup-client/files/10860749/log_receiver_chrome.txt)
[offer_answer_received_on_chrome.txt](https://github.com/versatica/mediasoup-client/files/10860752/offer_answer_received_on_chrome.txt)

**Comment by ibc** [comment]
Are you checking "rtp" logs in mediasoup side? Those would tell you if unrecognized RTP streams are being received and hence discarded. I cannot just accept moving back to legacy simulcast due to an unclear problem.

**Comment by filipi87** [comment]
Hi @ibc,

I have just tested with `mediasoup` `3.11.13`, and you can see the logs attached here.

There are two logs:
- One that I have defined a single encoding, which is working; Also works if I don't pass any encoding;
```
const encodings = [
  {maxBitrate: 680000, scaleResolutionDownBy: 1, maxFramerate: 30},
];
```

- The other where I have passed 02 encodings when creating the producer. And in this case It is not working.
```
const encodings = [
  {maxBitrate: 200000, scaleResolutionDownBy: 4, maxFramerate: 10},
  {maxBitrate: 680000, scaleResolutionDownBy: 1, maxFramerate: 30},
];
```

Comparing the logs, this log never shows up in the second case, where It is not working.

```
mediasoup:Channel [pid:30996] RTC::Producer::GetRtpStream() | ignoring RTX packet for not yet created RtpStream (ssrc lookup) +27ms\
mediasoup:WARN:Channel [pid:30996] RTC::Producer::ReceiveRtpPacket() | no stream found for received packet [ssrc:923445912] +21s\
mediasoup:Channel [pid:30996] RTC::Producer::CreateRtpStream() | [encodingIdx:0, ssrc:2491486641, rid:, payloadType:100] +1ms\
mediasoup:Channel [pid:30996] RTC::Producer::CreateRtpStream() | FIR supported +0ms\
mediasoup:Channel [pid:30996] RTC::Producer::CreateRtpStream() | NACK supported +0ms\
mediasoup:Channel [pid:30996] RTC::Producer::CreateRtpStream() | PLI supported +0ms\

```
[working_single_encoding.pdf](https://github.com/versatica/mediasoup-client/files/10925606/working_single_encoding.pdf)

[not_working_02_encodings.pdf](https://github.com/versatica/mediasoup-client/files/10925604/not_working_02_encodings.pdf)

**Comment by snnz** [comment]
mid is null in the 'produce' parameters - looks like the same as #263.

**Comment by ibc** [comment]
> mid is null in the 'produce' parameters - looks like the same as #263.

Looks like that. Please try with latest mediasoup-client v3.6.89. If problem still happens comment here and I will reopen the issue.
