### ISSUE TITLE
Detecting ICE connection that will never connect

### ISSUE THREAD

**Issue by ArmorDarks** [versatica/mediasoup-client#253]
### Problem

Under normal circumstances, in case of connection issues, the ICE connection should eventually fail. `connectionstatechange` event will fire, and the application will have the opportunity to do something with it.

However, if all ICE candidates error during the gathering, the connection will forever stay in a `new` state and `connectionstatechange` event will never fire.

Example:

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/4460311/227658640-60671ba9-d26c-4221-8e04-ac8985f891cd.png">

It will be possible to produce and consume, but actually, no data will be transmitted since there's no live candidate pair.

The client can check periodically for candidate pairs in stats and timeout, but there is a better way by using `RTCPeerConnection.onicegatheringstatechange` event.

If ICE `iceGatheringState` changes to `complete` and `connectionState` is still `new` - that means it's a dead end unless `restartIce()` will be invoked. It's a good opportunity for the application to warn the user that something went wrong.

However, right now, `mediasoup-client` doesn't expose the `iceGatheringState`, nor `onicegatheringstatechange` handler.

### Proposal

**Option 1:** Expose the `onicegatheringstatechange` event and `iceGatheringState` on the `Transport` so that application can check for it.

**Option 2:** Add a new `Transport` event which will fire on `pc.iceGatheringState === 'complete' && pc.connectionState === 'new'` that will indicate a connection that can't be established

### Caveats

`onicegatheringstatechange` has good [browser support](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icegatheringstatechange_event). If we want to cover even more browsers, we can rely on [`icecandidate`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event) event and `event.candidate === null`, which also indicates that the gathering is finished.

**Comment by ibc** [comment]
Will address in next weeks. Too busy with many other things. Thanks.

**Comment by thebongy** [comment]
Hi @ibc , can I take this change up in a PR?

About the `gatheringState`, we can have an API exactly similar to the `connectionState`, this should be straightfoward. (Along with the backward comatibility logic using the iceCandidate event as @ArmorDarks pointed out)

As for option 2, we can discuss this further, but this can be a seperate change, as doing option 1 itself would let users implement such checks in their code.

**Comment by ibc** [comment]
Sorry @thebongy, I just got 15 minutes and did it. https://github.com/versatica/mediasoup-client/pull/276
