### ISSUE TITLE
Make `appData` no longer read-only

### ISSUE THREAD

**Issue by alexciarlillo** [versatica/mediasoup-client#254]
## Feature Request

https://mediasoup.discourse.group/t/just-curious-why-appdata-is-read-only/5116 

Would be nice to be able to do:

```
consumer.appData = {...consumer.appData, ...someNewAppData}
```

Reference issue: https://github.com/versatica/mediasoup/issues/1043

**Comment by ibc** [comment]
Done in https://github.com/versatica/mediasoup-client/pull/257 and released.
