### ISSUE TITLE
pipeTransport connected but audio does not play

### ISSUE THREAD

**Issue by moein9gh** [versatica/mediasoup-client#256]
Hi awesome community , I have an issue with pipe transport and its that I have an voice call app and I want to use pipeTransport for creating a voice call between two peers in different hosts
I could connect consumer and producer which are related to each peer and all events triggered correctly step by step
finally I could connect two pipeTransports in different hosts but then I can’t hear any voice while all states and logs are correct
all recvTransports, sendTransports and pipeTransports trigger connect state
also newProducer and newConsumer events triggers correctly
both recvTransports triggered completed state

what can I do?

thanks for your attention.

**Comment by moein9gh** [comment]
and another important thing is after some amounts of time score of producer which created using webrtcTransport will change to zero and pipeTransport gets closed
for implementing this sample im using another sample project
link of sample that im following : https://github.com/craterone/mediasoup-pipetransport.git

**Comment by ibc** [comment]
Please use the mediasoup forum for questions/problems.

**Comment by moein9gh** [comment]
I sent my problem in mediasoup forum 8 days ago

**Comment by ibc** [comment]
That is not a valid excuse.
