### ISSUE TITLE
Make the implement of Transport simple?

### ISSUE THREAD

**Issue by richmonkey** [versatica/mediasoup-client#259]
## Feature Request
I found Transport contains new members(_pendingConsumerTasks, _pendingPauseConsumers,_pendingResumeConsumers,...) in the recent version.
I want to know why add these members, they makes code more complex.
I guess because our awaitQueue's task works slowly?
if true, can we make awaitQueue's task does't make any block net requests? 
I know do this change need to make a lot of changes to api.
Maybe our api is very high level,  the core of client is handler.
Maybe just expose handler(plus transport) is enough, no producer, no consumer.

No need  _pendingConsumerTasks, _pendingPauseConsumers  _pendingResumeConsumers... really makes the code more simple.

Last, i found mediasoup-client  don't support native ios&android (not react native), Do we need to support native ios&android client?
If need, I think i can do these works.

**Comment by ibc** [comment]
This is not a feature request but a question about the code. Please use the mediasoup forum to discuss about those topics.
