### ISSUE TITLE
Transport produce doesn't respect preferredPayloadType

### ISSUE THREAD

**Issue by flyingdove** [versatica/mediasoup-client#261]
## Bug Report

- Operating system: Windows 10
- Browser version: Chrome 113.0.5672.127 
- npm version: 16.19.1
- mediasoup version: 3.11.21
- mediasoup-client version: 3.6.82

### Issue description

Transport 'produce' method doesn't respect preferredPayloadType which is set in codec?: RtpCodecCapability of ProducerOptions. Because of this, it is impossible to choose neccesary codec when multiple codecs with same mimeType but different parameters.

[This is a mentioned in discussion group](https://mediasoup.discourse.group/t/multiple-mediacodecs-with-same-mimetype/3902)

**Comment by ibc** [comment]
Please keep the discussion on the forum unless you have a real and well documented bug to report. For now there is not.
