### ISSUE TITLE
Replace bowser dep

### ISSUE THREAD

**Issue by palashgo** [versatica/mediasoup-client#262]
### Your environment

- Operating system: Android
- Browser version: Chrome 104
- npm version: *
- mediasoup version: *
- mediasoup-client version: *

### Issue description

mediasoup-client uses `bowser` for browser detection and for switching to appropriate handlers.
[Bowser](https://www.npmjs.com/package/bowser) however is an unmaintained project, last update was published 3 years ago and there are tons of open issues

Example of one issue we faced in production is with this user agent (Chrome Android, Motorola Edge)

```
Mozilla/5.0 (Linux; Android 10; motorola edge) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36
```

This is how `bowser` parses this user agent

```
browser name: "Microsoft Edge"
os name: "Android"
version: "10"
engine name: "EdgeHTML"
version: ""
```

Which leads mediasoup-client to incorrectly use the Edge handlers instead of the Chrome handlers

One way to solve this would be to switch to a more modern and better supported user agent parsing library - [ua-parser-js](https://www.npmjs.com/package/ua-parser-js)

```
browser name: "Mobile Chrome"
os name: "Android"
version: "10"
engine name: "Blink"
version: "104.0.0.0"
```

Both these projects includes complete test suites, so a switch to ua-parser-js could be made asserting bowser tests so nothing that was working before would break

Another alternative is to switch to a feature based browser detection which would be more reliable and would solve for issues with browser wrappers and in app browsers

**Comment by ibc** [comment]
@palashgo please check this PR https://github.com/versatica/mediasoup-client/pull/266
