### ISSUE TITLE
Feature request: handler apis for getStats

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup-client#27]
It would be great if we could get client side stats exposed (https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/getStats). I know browser specs still different pretty wildly on delivering those, but just retrieving what we can would be great.

Let me know if you'd like me to add it as a PR.

**Comment by ibc** [comment]
mediasoup already provides stats, although they are generated in the server. Check the enableStats method in the client entities.

**Comment by artushin** [comment]
I'm looking for roundTripTime. I didn't see it in the server stats though, so I think it would be nice to expose it from the client.

**Comment by ibc** [comment]
AFAIR we do generate `rtt` in the stats. If not, may you open a different issue for this in the mediasoup server project?

**Comment by artushin** [comment]
Oops. `roundTripTime` right there on the outbound stats. My bad, thanks!

**Comment by ibc** [comment]
:)
