### ISSUE TITLE
Add a function to update turnServers dynamicaly in an existing room

### ISSUE THREAD

**Issue by misi** [versatica/mediasoup-client#28]
I would like to update the ICE server after the room has been created in mediasoup.client,
but unfortunately I didn't find a room function that I could use to update the turnServers.

Would it be possible to add a new function to Room object that updates RoomOptions->turnServers and this way I could restart ICE with the new turnServer?

I get a time limited long term (turn) credential from an API, so this is why I need this feature.

**Comment by misi** [comment]
It is more complicated or just as simple to update to the internal ICE Servers list and Restart ICE after it?
https://github.com/versatica/mediasoup-client/pull/29

**Comment by misi** [comment]
@ibc 
I need this feature, I know you are very busy but could you give me any estimation?
Or should I try to make PR?

**Comment by ibc** [comment]
Let me 2-3 weeks.

**Comment by misi** [comment]
Ok. Thx!

**Comment by ibc** [comment]
Hi, I cannot believe it but Firefox does not implement the `peerconnection.setConfiguration(conf)` API so TURN credentials cannot be updated.

**Comment by ibc** [comment]
Yep, just FF is missing.

**Comment by ibc** [comment]
Hi, mediasoup-client v3 will have this feature (not in FF, of course).

**Comment by misi** [comment]
Many Thanks..
