### ISSUE TITLE
DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to add remote stream ssrc: 901813733 to {mid: 7, media_type: video}

### ISSUE THREAD

**Issue by appamvenkatesh** [versatica/mediasoup-client#281]
Getting DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to add remote stream ssrc: 901813733 to {mid: 7, media_type: video} randomly, not able to understand the issue why it is coming, can anyone help me to solve this.

**Comment by ibc** [comment]
I'm afraid you are not even providing any useful info so please ask in the forum.
