### ISSUE TITLE
await sendTransport.produce is stuck. not response, don't resolve

### ISSUE THREAD

**Issue by quando12** [versatica/mediasoup-client#286]
`
this._micProducer = await this._sendTransport.produce({
        track: this._track,
        codecOptions: {
          opusStereo: 1,
          opusDtx: 1,
        },
      });
       console.log('this._micProducer 3333', this._micProducer)
`

Can't go console.log, It **stuck** in await  this._sendTransport.produce

**Comment by quando12** [comment]
please help me

**Comment by ibc** [comment]
Use the mediasoup forum for asking for help. Not here.

**Comment by quando12** [comment]
can you give for me forum link. please
