### ISSUE TITLE
'awaitqueue' reports an error after upgrading to version 3. There is no problem with version 2.

### ISSUE THREAD

**Issue by panhezeng** [versatica/mediasoup-client#287]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup-client.

If you have questions or doubts about mediasoup-client or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

### Your environment

- Operating system: window 10
- Browser version:
- npm version: 16.20
- mediasoup version: 
- mediasoup-client version: 3.7

### Issue description

ERROR in ./node_modules/mediasoup-client/node_modules/awaitqueue/lib/index.js 12:23
  Module parse failed: Unexpected token (12:23)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | class AwaitQueueStoppedError extends Error {
  |     constructor(message) {
  >         super(message ?? 'AwaitQueu

**Comment by ibc** [comment]
Use a modern version of webpack or use a loader in webpack to load AwaitQueue and mediasoup-client libs. They use modern JavaScript ES. This is not a bug.

If you need help ask in the mediasoup forum (not here in GitHub).

**Comment by panhezeng** [comment]
You should use babel loader and add AwaitQueue and mediasoup-client to the transpile configuration.

**Comment by panhezeng** [comment]
> Use a modern version of webpack or use a loader in webpack to load AwaitQueue and mediasoup-client libs. They use modern JavaScript ES. This is not a bug.
> 
> If you need help ask in the mediasoup forum (not here in GitHub).

You should use babel loader and add AwaitQueue and mediasoup-client to the transpile configuration ？
