### ISSUE TITLE
Cannot change the number of encodings with setParameters

### ISSUE THREAD

**Issue by alecpl** [versatica/mediasoup-client#293]
## Bug Report

I'm not sure it's a bug as it is just a warning Firefox 123.0 gives in the console:

"WARNING! Invalid setParameters call detected! The good news? Firefox supports sendEncodings in addTransceiver now, so we ask that you switch over to using the parameters code you use for other browsers. Thank you for your patience and support. The specific error was: Cannot change the number of encodings with setParameters".

### Your environment

- Operating system: Linux
- Browser version: Firefox 123
- mediasoup-client version: 3.6.57

**Comment by ibc** [comment]
This was a pending change. However first time I tried what the log says, it did NOT work. Now it does. On it.

**Comment by ibc** [comment]
Done.
Released in 3.7.6
