### ISSUE TITLE
No video and Audio when remote stream url is provided to RtcView.

### ISSUE THREAD

**Issue by ali-20** [versatica/mediasoup-client#294]
This issue is happening in iOS and Android, when integrating mediasoup-client in the react-native-app. Both users, involved in the call are receiving the track on consuming the producer, when converted that track to mediaStream and given to RtcView, it shows complete black screen with no audio/video whatsover.

Is there anyone who has experienced the same problem, please share your feedback. Thanks.

mediasoup-client Version: 3.6.100
react-native-webrtc Version: 106.0.0

**Comment by ibc** [comment]
Ask in the forum, please. We (and many others) use mediasoup-client in React Native apps and for sure such a problem doesn't happen to us so it's not a bug in mediasoup-client.

**Comment by ali-20** [comment]
Sure, Thanks for the help.
