### ISSUE TITLE
produce() does not perform strict match check on passed codec.

### ISSUE THREAD

**Issue by szt217** [versatica/mediasoup-client#296]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup-client.

If you have questions or doubts about mediasoup-client or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

### Your environment

- Operating system: MacOS
- Browser version: Chrome 123.0.6312.124
- npm version: 10.2.3
- mediasoup version: 
- mediasoup-client version: 3.7.6

### Issue description
Discourse topic for additional context
https://mediasoup.discourse.group/t/using-mediasoup-client-with-h264/5995

The mediasoup-client does not perform a strict match check on codecs when generating a producer, meaning it skips checks on codec parameters. When passing a codec into the produce() function, it will match on the first "non-strict" codec match it finds, which may not be the desired codec. 

This has been deemed a bug - a strict match check should be performed here.

**Comment by ibc** [comment]
Thanks for reporting. Fixed and version 3.7.7 released.
