### ISSUE TITLE
 enableMic() | failed:DataCloneError: Failed to execute 'structuredClone' on 'Window': #<Object> could not be cloned.

### ISSUE THREAD

**Issue by deadman962011** [versatica/mediasoup-client#309]
- Operating system: Windwos 10 pro 
- Browser version: Google Chrome Version 129.0.6668.101
- npm version:  9.8.1
- mediasoup version: ^3.7.17
- mediasoup-client version:

### Issue description 

hi am getting this error when enter meeting page on vueJs app with vite but when i use webpack its working 

![mediasoup-client error](https://github.com/user-attachments/assets/f08bebaa-b20e-4f38-998f-5cc99fa2c2e1)

**Comment by ibc** [comment]
This issue has been reported (and closed as invalid) many times already. Please check closed issues.

**Comment by deadman962011** [comment]
ok thank you ... checking
