### ISSUE TITLE
 Issue with Multiple Bitrates and Deprecated Methods in React Native

### ISSUE THREAD

**Issue by vaas2k** [versatica/mediasoup-client#313]
I encountered the following issues while using Mediasoup with React Native:

Multiple Bitrates Error:
When sending multiple bitrates, I receive the error:
[Error: Failed to set local offer sdp: Failed to add send stream ssrc: 2778429097 into m-section with mid='0']

Example encoding configuration:
encodings: [
  { rid: 'r0', maxBitrate: 450000, scalabilityMode: 'S1T3' },
  { rid: 'r1', maxBitrate: 300000, scalabilityMode: 'S1T3' },
  { rid: 'r2', maxBitrate: 900000, scalabilityMode: 'S1T3' },
]

Deprecated addStream in src/handlers/React Native:
The send and stopSending methods use addStream, which causes an undefined error in React Native. Replacing it with addTrack fixes the issue.

getRemoteStream Deprecation in the receive method:
Replaced getRemoteStream with getReceiver to avoid deprecation issues.

Suggested Fixes:

Improve handling of multiple bitrate encodings in React Native.
Update send/stopSending to use addTrack.
Replace getRemoteStream with getReceiver.

**Comment by ibc** [comment]
Assuming you are using a recent or newest version of react-native-webrtc, you have to use ReactNativeUnifiedPlan mediasoup-client handler rather than ReactNative handler. This is documented:

https://mediasoup.org/documentation/v3/mediasoup-client/api/#BuiltinHandlerName
