### ISSUE TITLE
Second producer.send call fails with "Track already exists"

### ISSUE THREAD

**Issue by ChrisE87** [versatica/mediasoup-client#34]
Hello everyone,

having kind of a weird problem that I just can't seem to resolve. I am using version 2.1.0 (also tested 2.0.16) of the mediasoup-client and have a local demo server set up for testing. Using a mediasoup-demo client with gulp live works just fine, I am having an Android implementation that also works fine with the server I am running. 

However, I can't seem to get it working when including it into an existing application. I used the simple example from the readme, but whenever I try to add the second producer, I get a "InvalidAccessError: Track already exists". 

It does not matter in which order I do it (video first or audio first), the second call always gives me this error. Debugged a bit and it happens specifically when doing "addStream" to the peerconnection in the addProducer call. The streams I am getting from the getUserMedia calls do have different IDs. 

Current code snippet (added a 5 sec delay for the second since I suspected racing conditions): https://pastebin.com/uSkFb4xR
I am getting into the "video send error" case. Started off with an exact copy of the example given (just one getUserMedia call etc.) and it was just the same.

Maybe I am just blind and oversaw something critical, but at the moment I am completely at a loss after 12 hours of trying to get this running, and am wondering if there is some kind of bordercase bug that leads to adding the same stream twice. 

Thanks in advance!

**Comment by ibc** [comment]
Please, use the public mailing list for questions and usage problems. This is the issue tracker.

BTW I don't know where "InvalidAccessError: Track already exists" error comes from. `mediasoup-client` does not generate such an error. Also, the `id` of the MediaStream is irrelevant. The important `id` here is the one in the MediaStreamTrack.

**Comment by vpavlov80** [comment]
I was having the same issue. It turned out that webrtc-adapter and mediasoup-client prior to 2.1.4 doesn't get along on Chrome. So just update to mediasoup-client 2.1.4 or greater. Here is the link to the discussion from the mailing list - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/mediasoup/_WPOr96MeKI.
