### ISSUE TITLE
Simulcast: reverse priority order

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client#35]
Low stream must have "high" priority and so on:

https://github.com/versatica/mediasoup-client/blob/60909bc038143dd45d9fea38121bfad48d423f92/lib/handlers/Firefox59.js#L150

**Comment by ibc** [comment]
https://tools.ietf.org/html/draft-ietf-rtcweb-transports-17#section-4

I'm not 100% sure. @flippo thoughts?

**Comment by ibc** [comment]
Related issue reported in webrtc-pc project: https://github.com/w3c/webrtc-pc/issues/1888

**Comment by fippo** [comment]
I would assume that low-resolution streams are watched by a larger fraction of clients (commonly; there are some use-cases where that is not true). In a low bandwidth situation I want to have high priority given to those while dropping the high-resolution stream.

But I agree the definition is quite vague...

**Comment by ibc** [comment]
I agree with your rationale. What it's not clear for me is that the spec states that. In fact, the spec states nothing useful. Let's see if somebody says something in the webrtc-pc issue.

**Comment by ibc** [comment]
2.1.1 released. Thanks!
