### ISSUE TITLE
Implement p2p mode 

### ISSUE THREAD

**Issue by so010** [versatica/mediasoup-client#39]
Would be nice to have a possibility to connect clients directly. This is something implemented in jitsi-meet as well and is important for scaling and privacy.

For jitsi description see: https://jitsi.org/news/p2p4121

**Comment by ibc** [comment]
Please, let's use the mailing list for questions and/or suggestions.

Anyway. The answer, for now, is no. mediasoup is not a full application (as Jitsi is). It's up to you how to design your client and server side applications. You may, for example, avoid mediasoup if there are just two participants. This is up to your app.
