### ISSUE TITLE
Support react-native-webrtc

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client#5]
* https://github.com/oney/react-native-webrtc

**Comment by ibc** [comment]
Working on it: db3528dcbdb477764faba241548570c34cb1db1b

**Comment by ibc** [comment]
First problem when in iOS: https://github.com/oney/react-native-webrtc/issues/401

**Comment by ibc** [comment]
So the first problem may have been bypassed with this commit: d77f4a48673114f815f538599b75ab752752b7bc

**Comment by thehappycoder** [comment]
@ibc Do you have video publishing working now that you have https://github.com/ibc/libsdptransform or there is still more work to be done to get first green path?

**Comment by thehappycoder** [comment]
Can you share the source code for the demo you are building? After adding https://github.com/versatica/mediasoup-client.git#react-native, protoo-client, and events packages, I connected to the websocket and did `room.join`, which crashed with an error:
ReferenceError: Can't find variable: RTCPeerConnection because such class doesn't exist in react-native land. I don't see you importing it from `react-native-webrtc`

**Comment by ibc** [comment]
libsdptransform is needed bt the future mediasoup-client-native (built in C++). This task is about using react native plus react-native-webrtc, so mediasoup-client (JS) itself should work. Of course, it needs react-native-webrtc.
We are working on it.

**Comment by ibc** [comment]
However, let's keep please this issue clean with just comments about its progress.

**Comment by ibc** [comment]
Another big limitation in `react-native-webrtc`: [Cannot use a new create MediaStream to display a local or remote video track](https://github.com/oney/react-native-webrtc/issues/405)

Basically `react-native-webrtc` assumes that the only `stream` objects that the app is gonna use are those `streams` generated by `react-native-webrtc` (via `getUserMedia` or `setRemoteDescription`).

This is a heavy limitation for `mediasoup-client` which is not designed to depend on the original `MediaStream` at all. So bad news.

**Comment by ibc** [comment]
NOTE: **mediasoup-client 2.0.7** works with [react-native-webrtc](https://github.com/oney/react-native-webrtc/).

**Comment by nxz91** [comment]
Hi @ibc, when you say it works you mean it works without modifications except video tracks? Audio connections should be fine?

**Comment by nxz91** [comment]
A few fun facts:

```  "dependencies": {
...,
    "mediasoup-client": "^2.0.16",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-webrtc": "^1.58.3",
  }```

**Comment by nxz91** [comment]
Hi Iñaki,

Okay, I just add to `yarn add events` to not get this issue any more. I also had to `import * as mediasoupClient from 'mediasoup-client'` instead of simply `import mediasoupClient from 'mediasoup-client'`.

**Comment by ibc** [comment]
The former is a real fix. Indeed the "events" module is required. It just happens that browserify includes it, but webpack doesn't. It will be added.

The second problem is a bad ES6 module usage in your code ;)

**Comment by herlarb** [comment]
@ibc  Any updates on fixing this issue

**Comment by ibc** [comment]
@nxz91: mediasoup-client 2.0.17 includes the "events" module. Thanks for reporting.

**Comment by ibc** [comment]
@herlarb I don't know which issue you mean. However, if it's not related to the topic of this issue let's discuss it in the mediasoup mailing list.

**Comment by sachalegrand** [comment]
@ibc Hello, so is it currently possible to have a react-native app connect to a mediasoup server using react-native-webrtc and mediasoup-client, as of today?

**Comment by ibc** [comment]
@sachalegrand no, sorry. Check https://github.com/versatica/mediasoup-client/issues/5#issuecomment-359541129.

The patch to apply in react-native-webrtc is somewhere in a thread in the mediasoup mailing list.

**Comment by buithi** [comment]
Hi @ibc, I built MediaStream but cannot show on either RTCView of react-native-webrtc or Video of react-native-video. Are you way to show this?

![image](https://user-images.githubusercontent.com/568664/47335107-cc4eb380-d6b3-11e8-932d-443523aa445f.png)

**Comment by Sharcoux** [comment]
I made a PR about it just now.

**Comment by ibc** [comment]
react-native-webrtc is not gonna evolve at all and will remain using the WebRTC API of 2003 (poorly implemented) for long. We may take a different approach as explained here:

https://github.com/versatica/libmediasoupclient/issues/40

**Comment by philjoseph** [comment]
I am planning to use WebRTC only for audio and may be also pictures but not video. Is mediasoup with react-native-webrtc with the patch an appropriate solution, do you believe ? Shall we better help you developing your react-native client lib as posted in versatica/libmediasoupclient#40 ?

**Comment by ibc** [comment]
I'm on holidays for two weeks and have lot of mediasoup related work after it. Ping here after some weeks and will discuss it again. Right now I don't have any idea of why the proper way to go is.

**Comment by ibc** [comment]
Hi, after the excellent work by @saghul in react-native-webrtc 1.75.0, I've modernized mediasoup-client v3 for React-Native.

In theory, no external hacks are needed. The application can now create `MediaStream` instances safely, call `addTrack()` on them with remote tracks provided by `consumer.track`, etc.

**Comment by saghul** [comment]
👍 

FTR there is no way to detect the react-native-webrtc version so I suggest you just put a comment saying that >= 1.75 is required.

**Comment by ibc** [comment]
Related to #86:

mediasoup-client won't include the whole react-native-webrtc as dependency, that would be terribly inappropriate.

@saghul can you help please? The problem seems to be that mediasoup-client depends on `RTCPeerConnection`, `RTCSessionDescription` and `MediaStream` in the global namespace.

* mediasoup-client **cannot** (or should not) call `require("react-native-webrtc")` internally.
* Does react-native-webrtc expose some API to pollute the global namespace?
* Or perhaps the [ReactNative.js](https://github.com/versatica/mediasoup-client/blob/v3/lib/handlers/ReactNative.js) handler could dynamically use `const { RTCPeerConnection } = require("react-native-webrtc")`, etc when needed? (so it would throw just in runtime if react-native-webrtc is not found)?
   * Is it a good practice to depend on runtime `require()` semantics within React-Native? or is it a super hack?

Other than that, any suggestion on what the best way to go is? A hack coming to my mind:

* Document that the application must require "react-native-webrtc" and pollute the global namespace before it creates a mediasoup-client `Device` instance.

**Comment by saghul** [comment]
I’d say ReactNative.js should require it. You could have react-native-WebRTC as an optional dependency perhaps.

**Comment by saghul** [comment]
I do think that adding some API for exporting stuff as globales makes sense, I’ll do that too.

**Comment by ibc** [comment]
> I’d say ReactNative.js should require it. You could have react-native-WebRTC as an optional dependency perhaps.

Optional deps do not work "fine". I don't want that react-native-webrtc is installed if I use npm to add mediasoup-client into my web project.

**Comment by ibc** [comment]
> I do think that adding some API for exporting stuff as globales makes sense, I’ll do that too.

In cordova-plugin-iosrtc we exposed [iosrtc.registerGlobals()](https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/docs/iosrtc.md#iosrtcregisterglobals).

**Comment by ibc** [comment]
Just in case I've opened an issue in react-native-webrtc project: https://github.com/react-native-webrtc/react-native-webrtc/issues/685

**Comment by ibc** [comment]
So this is done.
