### ISSUE TITLE
Safari does not play the received tracks

### ISSUE THREAD

**Issue by JSteitz** [versatica/mediasoup-client#51]
Safari is receiving the streams but can't play them. I don't get any errors in the console and I don't really know if it is the server, the client or the browser itself that has a problem.
I attached the debug output from mediasoup for server and both clients (publisher and subsriber).

Publishing with Safari works only in direction to Chrome as subscriber and Firefox only receives 1fps.
But this is a different problem and I will create a new issue if you think it's a bug.

What I tried to do:

* playing with the codec
* using an actual server instead of localhost
* using ssl on server
* tried to use Safari as publisher (works only with Chrome as subsriber - Safari to Safari has the same problem)

MacOS: 10.14
Safari: 12
Firefox: 63

```js
const MEDIA_CODECS = [
  {
    kind: "audio",
    name: "opus",
    clockRate: 48000,
    channels: 2,
    parameters: {
      useinbandfec: 1
    }
  },
  {
    kind: "video",
    name: "H264",
    clockRate: 90000,
    parameters: {
      "packetization-mode": 1,
      "profile-level-id": "42e01f",
      "level-asymmetry-allowed": 1
    }
  }
]
```

Logs
[mediasoup-client-publisher.log (Firefox)](https://github.com/versatica/mediasoup-client/files/2542130/mediasoup-client-publisher.log)
[mediasoup-client-subscriber.log (Safari)](https://github.com/versatica/mediasoup-client/files/2542131/mediasoup-client-subscriber.log)
[mediasoup-server.log](https://github.com/versatica/mediasoup-client/files/2542132/mediasoup-server.log)

**Comment by ibc** [comment]
Just tested the mediasoup-demo with those codecs above. Tested in OSX 10.14 with Safari stable. It works. Video is shown in both browsers (Chrome and Safari).

NOTE: In Safari you can just have a single tab using the webcam.

**Comment by telephant** [comment]
maybe you can check if the audio autoplay failed. 

in safari, if there is a async function in  audio.play(), it will not play successfully
