### ISSUE TITLE
[react native] Error: Couldn't find preset "@babel/env" relative to directory 

### ISSUE THREAD

**Issue by mkjiau** [versatica/mediasoup-client#59]
it's my `packages.json`:   
```
"mediasoup-client": "^2.4.0",
"react": "16.3.1",
"react-native": "0.55.1",
```

When I'm launching my RN app (android) in dev mode, get this error:    
```
error: bundling failed: Error: Couldn't find preset "@babel/env" relative to directory "....\\node_modules\\mediasoup-client"
```

what babel packages or configs I should do? thanks~

**Comment by ibc** [comment]
Honestly no idea and we cannot help with this issue right now. Please, move this question to the mediasoup mailing list so may be other users can help.
