### ISSUE TITLE
Uncaught TypeError: sdp.media[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by mkjiau** [versatica/mediasoup-client#60]
There's a transpiler issue that failed to transpile codes into `lib-es5`.

For instance, in [line 21](https://github.com/versatica/mediasoup-client/blob/886369c5c91b732649a7f4893098134327a5d543/lib/handlers/sdp/commonUtils.js#L21) of `lib/handlers/sdp/commonUtils.js`: 
```
for (const m of sdpObj.media) { ...
```
transpiled to:
```
for (var _iterator = sdpObj.media[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) { ...
```
it will throw `Uncaught TypeError: sdp.media[Symbol.iterator] is not a function`  as [Iteration_protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols), pure js object is not iterable.

The best way to solve it is to refactor the codebases by replacing 
```
for (const m of sdpObj.media) { ...`
```
with 
```
for (const m of Object.values(sdpObj.media)) { ...` 
```
for reference: https://github.com/babel/babel-loader/issues/84

BTW, I'm working on React-Native with mediasoup-client, the workaround to this issue just changes the nodejs entrypoint from "lib-es5/index.js" to "lib/index.js" as `package.json` below: 
```
  ...
  "homepage": "https://mediasoup.org",
  "license": "ISC",
  "main": "lib/index.js",
  "name": "mediasoup-client",
  ...
```

any suggestion? `mediasoup` is great 👍

**Comment by ibc** [comment]
> The best way to solve it is to refactor the codebases by replacing
> 
> ```
> for (const m of sdpObj.media) { ...`
> ```
> with
> 
> ```
> for (const m of Object.values(sdpObj.media)) { ...` 
> ```

This is wrong. `sdpObj.media` is an Array and not an Object, so using `Object.values(sdpObj.media)` does not make sense. The issue is elsewhere.


> for reference: [babel/babel-loader#84](https://github.com/babel/babel-loader/issues/84)
> 
> BTW, I'm working on React-Native with mediasoup-client, the workaround to this issue just changes the nodejs entrypoint from "lib-es5/index.js" to "lib/index.js" as `package.json` below:
> 
> ```
>   ...
>   "homepage": "https://mediasoup.org",
>   "license": "ISC",
>   "main": "lib/index.js",
>   "name": "mediasoup-client",
>   ...
> ```

I'd like to move `main` to point to the untranspiled entry point (`lib/index.js`). However, have you tested that it still works in Chrome, Firefox and Safari that way?

**Comment by ibc** [comment]
BTW, in mediasoup v3 `package.json` will no longer export a ES5 transpiled/babelized version, so `"main"` will point to the ES6 `lib/` folder.
