### ISSUE TITLE
Chromium browsers NOT supported

### ISSUE THREAD

**Issue by 2002demon** [versatica/mediasoup-client#62]
Now i use this client v2, but this does not support a lot of Chrome based browsers.
YandexBrowser is popular in Russia, is based on Chrome 71. A lot of various browser the same.
Plese add some code to your Device.js file in _detect() at last:

```
			else if (ua.search('Chrome')!=-1)
			{
				Device._flag = 'chromium';
				Device._handlerClass = Chrome70;
			}
```

**Comment by ibc** [comment]
As you may understand, we cannot assume that **any** unknown/undetected browser is "Chromium", and checking `ua.search('Chrome') != -1)` is not a robust solution (some browsers indicate "Chrome" into their User-Agent, such as MS Edge).

May you please paste here the exact User-Agent string of your browser?

**Comment by 2002demon** [comment]
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 YaBrowser/18.11.1.805 Yowser/2.5 Safari/537.36`

In your code is allowed only Chrome/FF/Opera, but its many browsers based on Chromium with another names. So if you check it at the last "else if" condition, it will be most better. Adding 10 new browser names is bad solution. And selection based on browser version is bad solution too. Using function checks and properties is better.

Do you know, **Chrome 49** (last version on XP) does  not work by mediasoup-client, its not ok.
I had my own old little JS client supported all chrome versions/OS from 25 to 71 without any problems. But my code was based on medisoup v1 (unstable tor me), und change it to v2 was to complex. So i use now your client, und need to fix some things.

And your file **dist/mediasoup-client.js is NOT ES5**. At the end of file added some 3th-Party node libs  based on ES6. Please fix it if possible. You can found function abstraction: **() => {}** - not included in ES5, and another things. If your client used by IE11, errors breaks another JS. IE11 is ES5 compatible and default on Windows 7,8, vista.

Investigation of 2 days and tests on 100 rooms.

**Comment by ibc** [comment]
> `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 YaBrowser/18.11.1.805 Yowser/2.5 Safari/537.36`

Thanks.
 
> In your code is allowed only Chrome/FF/Opera, but its many browsers based on Chromium with another names. So if you check it at the last "else if" condition, it will be most better. Adding 10 new browser names is bad solution. And selection based on browser version is bad solution too. Using function checks and properties is better.

"Using function checks and properties is better" based on what? I know what each browser supports (regarding WebRTC) regarding its exact version.


> Do you know, **Chrome 49** (last version on XP) does not work with mediasoup-client, its not ok.

Is there people still using Windows XP?


> I had my own old little JS client supported all chrome versions/OS from 25 to 71 without any problems. But my code was based on medisoup v1 (unstable tor me), und change it to v2 was to complex. So i use now your client, und need to fix some things.

We'll do something to detect other Chromium based browsers, but without knowing which exact Chromium they use internally it's hard to figure out which "WebRTC handler" assign to them. So it will be a best effort and it will assume that any unlisted Chromium based browser uses the **latest** Chromium stable version internally.


> And your file **dist/mediasoup-client.js is NOT ES5**. At the end of file added some 3th-Party node libs based on ES6. Please fix it if possible. You can find function abstraction: **() => {}** - not included in ES5, and another things. If your client used by IE11, errors breaks another JS. IE11 is ES5 compatible and default on Windows 7,8, vista.

The world evolves. We never said that `dist/mediasoup-client.js` is pure ES5. In fact, you should install mediasoup-client within your applicationusing npm, yarn or other package managers. And then, if you need to generate a pure ES5 JavaScript bundled file, use Babel, [terser](https://www.npmjs.com/package/terser), etc.

FYI we are now working on mediasoup and mediasoup-client v3, and mediasoup-client v3 will not include any `dist/xxx` file and it's coded using ES6 everywhere. It's up to the application developer to transpile libs and dependencies if required for its own application needs.

**Comment by 2002demon** [comment]
XP uses 2% of people, Chrome 49 uses 1% of people becouse this version is lattest on XP.
https://imgs.su/upload/186/2659812333.jpg

mediasoup-client.js is bundled from lib-es5, i tried to bundle another packages as es5 but whithout luck,  i have not enough knowleged for node/gulp, i use this tools only for mediasoup.

I know about v3, and i try to remove support for old browser by all my JS aplications, but currently i have many complaints about problems with webcams. Support maximum of possible - is nice thing.
I will try to add support for Chrome 49.

Anyway, thanks for your good work.

**Comment by ibc** [comment]
> XP uses 2% of people, Chrome 49 uses 1% of people becouse this version is lattest on XP.
> https://imgs.su/upload/186/2659812333.jpg

I'll add best-effort support for unknown Chromium based browsers and notify here when done.
 

> mediasoup-client.js is bundled from lib-es5, i tried to bundle another packages as es5 but whithout luck, i have not enough knowleged for node/gulp, i use this tools only for mediasoup.

There are tons of JS libraries today that are just ES6. The application developer that uses them is responsible of transpiling them to ES5 if desired. This is something the application developer must deal with. You can read the documentation of the **terser** library I mentioned above and use it.

**Comment by ibc** [comment]
Unknown Chromium based browser detection is done in 2.4.7 released right now. Hope it helps.

**Comment by 2002demon** [comment]
I tried to add support for Chrome 49 used Chrome 55 class, but without luck. Can't fix error:
Uncaught (in promise) TypeError: Failed to execute 'createOffer' on 'RTCPeerConnection': The callback provided as parameter 1 is not a function. (...)
Played with this code, no progress :(
`		return pc.createOffer(
			{
				offerToReceiveAudio : true,
				offerToReceiveVideo : true
			})
			.then((offer) =>
			{
				try { pc.close(); }
				catch (error) {}

				const sdpObj = sdpTransform.parse(offer.sdp);
				const nativeRtpCapabilities = sdpCommonUtils.extractRtpCapabilities(sdpObj);

				return nativeRtpCapabilities;
			})
			.catch((error) =>
			{
				try { pc.close(); }
				catch (error2) {}

				throw error;
			});`

Tnx for commit, works too.

**Comment by ibc** [comment]
I'm afraid Chrome 49 is **too** old that it uses the super old WebRTC API based on callbacks instead of Promises. So, for example, instead of:

```js
pc.createOffer()
  .then((offer) => { ... })
  .catch((error) => { ... })
```

it uses:

```js
pc.createOffer(
  (offer) => { ... },  // callback
  (error) => { ... }   // errback
);
```

Such a super old callback based API was used in 2013 and before! You can check it [here](https://www.w3.org/TR/2013/WD-webrtc-20130910/).

**Comment by 2002demon** [comment]
Thanks for info. 
I wondering why new construction worked by me from Chrome 25 to 71.
I forgot to add: https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/4.0.2/adapter.min.js
With this lib Chrome 49 work perfectly based on your Chrome 55 Class. (without correction)
Just changed here:

> 			else if (bowser.check({ chrome: '49', chromium: '49' }, true, ua))
> 			{
> 				Device._flag = 'chrome';
> 				Device._handlerClass = Chrome55;
> 			}

Chrome 49 was important for me to support XP and +2% of people. (+ last FF on XP work too)
Just as INFO.

**Comment by ibc** [comment]
Have you checked the new version 2.4.7? Assuming you add adapter.js, it will assign Chrome70 handler for Chrome 49. Can you test if it also works (so you don't need to keep a modified mediasoup-client code)?

**Comment by 2002demon** [comment]
Does not work with class 70 => "pc.addTransceiver is not a function"
Class 55, 67, 69 => SUCCESS

**Comment by ibc** [comment]
ok, so the required version is Chrome 49, right? if so I can do some trick to use Chrome55 handler.

**Comment by 2002demon** [comment]
Chrome 49 is important for me.
Maybe that? If not work, then not work, so or so.
else if (bowser.check({ chrome: '23', chromium: '23' }, true, ua))

**Comment by ibc** [comment]
Please, checkout mediasoup-client branch v2. I've added a [trick](d4b0d0c1f3e17a435cc64ae302c82bd6edcaca70). Let me know if it works.

**Comment by 2002demon** [comment]
Again after a lot of testing.
Best solution is to completly remove your last commit about Chrome 49 and fix this:

```
			// Best effort for Chromium based browsers.
			else if (browser.chromium || browser.blink || browser.webkit)
			{
				logger.warn('best effort browser detection [name:"%s"]', browser.name);

				Device._flag = 'chrome';
				Device._handlerClass = Chrome55;
			}
```

As you see, all undetected Chromium based browser uses Chrome55 + adapter.js.
Yandex Browser (chrome/70) - OK
Chrome 49 - OK
+ Samsung Browser (chrome/65) - OK
+ more other browsers/devices...
You can add global.adapter to be clean, works too.

And i found mediasoupClient.setDeviceHandler(handler, metadata), i can manage Classes from my script.

**Comment by ibc** [comment]
I'm not gonna assume that any Chromium based browser should use the older `Chrome55` handler. There are reasons to use newer versions (such as lack of support for `RtpSender.replaceTrack()` in Chrome 55 and older.

mediasoup-client will not include adapter.js.

Can you please confirm if mediasoup-client branch `v2`works with adapter.js in your Chrome 49 and it's detected as Chrome 55 (as this [commit](d4b0d0c1f3e17a435cc64ae302c82bd6edcaca70) is supposed to do? Please confirm it.

**Comment by 2002demon** [comment]
I confirm, tested this yesterday.
I understand you, replaceTrack is good thing and all go to Unified Plan.
Whats about this way in the last Chromium check? 

```
Device._flag = 'chrome';
Device._handlerClass = Chrome55;

var match=ua.match(/(Chrome)( |\/)(\w+)/i);  
var version=0; if(match) version=match[3];
if(version>=67) Device._handlerClass = Chrome67;
if(version>=69) Device._handlerClass = Chrome69;
if(version>=70) Device._handlerClass = Chrome70;
```

**Comment by ibc** [comment]
Can you please confirm that **all** (or most of) Chromium based browsers include the corresponding `Chrome/XX` in their User-Agent?

**Comment by 2002demon** [comment]
I think yes. I have checked only those, are not worked earlier: 
Yandex, Samsung Browser, Opera
If i found another problems, i can post here.
People say to me - it is all right. For me its currently solved.

**Comment by ibc** [comment]
Hi @2002demon, can you please update the v2 branch and try again? I did [this](https://github.com/versatica/mediasoup-client/commit/07a3192b3822de61692ecf44c420faa7f0c51795). It should:

* Use Chrome55 handler when in Chrome 49.
* Use Chrome70 handler when Yandex Browser.

Can you confirm it please so I'll release a new version?

**Comment by 2002demon** [comment]
NO. 
Why do you have added ( ) here => ((Chrome|Chromium))  ?
match[3] is /, **need to use match[4]**, or remove double ( ).
With match[4] work correctly.

At the moment i have found a new bug or strange thing.
I tried to reproduce rejoining without reload browser: 
join => leave => join 
but everything is wrong on client lib side.
First join is OK, after room.leave(); 3 sec ago i run again:

```
		room.join(peerName)
			.then(function(peers) {
				console.log('JOINED as '+peerName);
...
			})
...
```
 
and this join() function call 2 request to server with queryRoom and the same peerName => so we have doublicate Peer. And user is not joined, becouse 2 step 'join' request does not sended to server.
Any idea why this double queryRoom request can be?

**Comment by ibc** [comment]
> NO.
> Why do you have added ( ) here => ((Chrome|Chromium)) ?
> match[3] is /, **need to use match[4]**, or remove double ( ).
> With match[4] work correctly.

Yep, fixed in bec7675a64aaa16630ddbea374df6d9692ea10b3. I've included Chromium because some Chromium based browsers may indicate "Chromium" instead of "Chrome" in the User-Agent.


> At the moment i have found a new bug or strange thing.
> I tried to reproduce rejoining without reload browser:
> join => leave => join
> but everything is wrong on client lib side.
> First join is OK, after room.leave(); 3 sec ago i run again:
> 
> ```
> 		room.join(peerName)
> 			.then(function(peers) {
> 				console.log('JOINED as '+peerName);
> ...
> 			})
> ...
> ```
> and this last **join() function call 2 request to server with queryRoom and the same peerName** => so we have doublicate Peer. And user is not joined, becouse 2 step 'join' request does not sended to server.
> Any idea why this double queryRoom request can be?

Please, let's not mix different issues or usage problems in this issue report. Your issue is that you are setting `room` events twice in your code, probably below the `room.join()` line. Look at [here](https://github.com/versatica/mediasoup-demo/blob/master/app/lib/RoomClient.js#L667).

Anyway, please use the public mailing list for this kind of usage problems.

**Comment by 2002demon** [comment]
Checked, its work. I understand about chromium, my question was, why do you use DOUBLE round brackets **((**Chrome|Chromium**))** and not just:
const match = ua.match(/(Chrome|Chromium)[ /](\w+)/i);

I see you have removed Chrome69 in v3, why not removed in v2?
I think Chrome55 class would work up to 70 version, that just does not use replaceTrack  and single mediatracks. Just idea to think about it. My replaceTrack solution for all browsers is:
```
if(audioTrack && audioProducer && sendTransport) {
	audioProducer.close(); 
	audioProducer = room.createProducer(audioTrack); 
	audioProducer.send(sendTransport);
}
```

Thanks for removeAllListeners(), you are right 👍

**Comment by ibc** [comment]
> Checked, its work. I understand about chromium, my question was, why do you use DOUBLE round brackets **((**Chrome|Chromium**))** and not just:

That's not what bec7675a64aaa16630ddbea374df6d9692ea10b3 contains. I use `?:` for good reasons.

> I see you have removed Chrome69 in v3, why not removed in v2?

Because yes. And honestly, I feel like I should not give so many explanations.


> I think Chrome55 class would work up to 70 version, that just does not use replaceTrack and single mediatracks. Just idea to think about it. My replaceTrack solution for all browsers is:
> 
> ```
> if(audioTrack && audioProducer && sendTransport) {
> 	audioProducer.close(); 
> 	audioProducer = room.createProducer(audioTrack); 
> 	audioProducer.send(sendTransport);
> }
> ```

So it's like you are suggesting that we should just use Chrome55 for all Chrome >55 "because you think it works"? Well, just a big not. There are good reasons to follow the latest spec and the latest implementations rather than keeping old and deprecated API. And regarding `replaceTrack()`, your code above it not the same at all.

**Comment by 2002demon** [comment]
Not so. I suggested Chrome55 for 55-69 and leave Chrome70 for 70+.
Ok, sorry, no questions more.

**Comment by ibc** [comment]
Ok, don't worry and thanks for reporting.
