### ISSUE TITLE
error communication TypeError RTCIceServer / TURN / STUN servers configuration

### ISSUE THREAD

**Issue by lakano** [versatica/mediasoup-client#68]
Hello! 
I'm trying to set a TURN server, because of firewall restrictions for some users. So, on the v2.4.9, I've set this roomOptions to the mediasoupClient.Room(roomOptions) : 

```
     roomOptions: {
       turnServers: [
         new RTCPeerConnection({ iceServers: [
           { urls: 'stun:turn.myserver.com' },
           { urls: 'turns:turn.myserver.com', username: 'myuser', credential: 'mypassword', credentialType: 'password' },
         ]}),
       ],
     }

```
And I get this error on Firefox ( 66 on Linux, 65 on Windows )
error communication TypeError: "Missing required 'urls' member of RTCIceServer"
And this error on Chrome 72 (Windows and Linux):
error communication TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCIceServer

I known the format have changed ( before the property was 'url' and not 'urls', and username wasn't a property). Here is the good format: https://w3c.github.io/webrtc-pc/#rtciceserver-dictionary 

I've also tried to replace 'turns:' (port 443) to 'turn:', but doesn't help.

May be the lib mediasoup client doesn't support the new format, or may be there is something wrong in my configuration ?

Thanks for your help!

**Comment by ibc** [comment]
mediasoup-client does nothing with the given `iceServers` other than passing them verbatim to the PeerConnection. In your case there is a syntax error:

* Bad: `urls: 'turns:turn.myserver.com'`
* Good: `urls: 'turns:turn.myserver.com?transport=tcp'`

**Comment by lakano** [comment]
@ibc I've added « ?transport=tcp » at the end of my TURN url, but the same error occured.
Could this be a problem on the TURN server configuration (not sure at 100% my coturn server is correctly set! )

**Comment by ibc** [comment]
mmm, wait, why are you using this kind of "object" that includes a PeerConnection into `turnServers`?:

```
     roomOptions: {
       turnServers: [
         new RTCPeerConnection({ iceServers: [
           { urls: 'stun:turn.myserver.com' },
           { urls: 'turns:turn.myserver.com', username: 'myuser', credential: 'mypassword', credentialType: 'password' },
         ]}),
       ],
     }
```

It should be just this:

```
roomOptions: {
  turnServers: [
     { urls: 'stun:turn.myserver.com' },
     { urls: 'turns:turn.myserver.com;transport=tcp', username: 'myuser', credential: 'mypassword', credentialType: 'password' }
  ]
}
```

Why are you passing an entire `new RTCPeerConnection` to `turnServers`?

**Comment by lakano** [comment]
Thanks ! I've misunderstood the API documentation ( turnServers: sequence<RTCIceServer> )
