### ISSUE TITLE
MediaTrack.applyConstrains working not well after create a producer using the track

### ISSUE THREAD

**Issue by Royal-Chan** [versatica/mediasoup-client#69]
The case is, I want to change the video resolution after created a producer like this

```javascript
videoProducer.track.applyConstraints({
    width: { ideal:1280 },
    height: { ideal: 960 }
}).then(()=> {
    console.log("success")
})
```
After success, I have checked video tag videoHeight and videoWidth properties and it showed 640*480. It will throw `overConstraintsException` if I use `exact` instead of `ideal`. And I have done the same action for `videoProducer.originalTrack`, not work either.

But, if I close the video producer using `videoProducer.close()` or never create any producer use the track, it becomes 1280 * 960. So my webcam can support this resolution. 

I have found video producer will copy the track and hold it, I don't know if it's the case and how to resolve it. Now, I have to close producer first when I want to change any constraints, is there a more graceful solution?

**Comment by ibc** [comment]
First: the `track` being internally used by the underlying PeerConnection is `producer.track` and not `producer.originalTrack`, so you just need to apply changes on `producer.track`. Whether it's a cloned track or not (it is) does not change anything here.

I don't know how browsers react when calling `applyConstraints()` on a `track` they are sending on PeerConnection, but mediasoup and mediasoup-client do nothing to avoid or ignore such a behavior.

Said that, no matter what the resolution of the video track is. The PeerConnection will decrease it if it detects packet lost of too much CPU usage. There is a PeerConnection constraint to change that behavior. Again, not mediasoup specific.
