### ISSUE TITLE
Transport connection state changed to failed

### ISSUE THREAD

**Issue by subsub** [versatica/mediasoup-client#7]
I try to install mediasoup in my server from code. I clone the demo repo into my server and run npm install on both app and server. Then I run server.js, and set my nginx to point out server/public folder.
But I get this error which results in no media being transfered:
```javascript
mediasoup-client:Transport Transport connection state changed to failed
```
mediasoup-client:Transport Transport connection state changed to failed

Does any body know how to fix this?
Thank you

**Comment by subsub** [comment]
When I use firefox, it gives extra log like this:
```
ICE failed, add a STUN server and see about:webrtc for more details
The MediaStream passed to createMediaStreamSource has a cross-origin resource, the node will output silence.
```

**Comment by ibc** [comment]
Please, use the mailing list for questions. This is not a bug/issue in `mediasoup-client`.

BTW: If your server has private IP (AWS, Google Cloud Engine, Azure, etc) you must redirect the public IP to it, and must set `rtcAnnounceIPv4` in the mediasoup Server settings:

https://mediasoup.org/documentation/mediasoup/api/#Server-ServerSettings

Please, always read the doc. The demo is not supposed to just work no matter where you deploy it. Some tuning is required in certain cases.
