### ISSUE TITLE
Problem with H264 chrome 73

### ISSUE THREAD

**Issue by vadympetryshyn** [versatica/mediasoup-client#72]
After updating chrome to version 73, using H264 codec, can't see the video of broadcaster (black screen), it seems the problem in getting requestConsumerKeyFrame, because after effective profile change, the video is appeared. It regards v2 of mediasoup, can see on mediasoup demo as well

**Comment by ibc** [comment]
Can not reproduce it here using Chrome 73.0.3683.75 with H264 codec. Tested in the v2 demo.

Hard to believe that there is a bug in key frame handling in v2 (it would have generated many issues in the past if so). Also, `requestConsumerKeyFrame()` is just a cosmetic method to force a keyframe via JavaScript. Irrelevant here.

**Comment by ibc** [comment]
Also, just in case check [this](https://github.com/versatica/mediasoup/issues/264).

**Comment by vadympetryshyn** [comment]
The problem is not in paused stream. You can go here https://v2demo.mediasoup.org/?roomId=77kro2l6&forceH264=true after enter in another computer, all gonna looks fine, but if you start reload browser on first computer (several times until you catch) you definitely get the black screen on broadcaster's video, here is screenshot http://joxi.ru/Dr8BYQEcoolDZ2

**Comment by ibc** [comment]
Did ton of tests. The only I get, sometimes, is black screen in the receiver for just less than a second. It may be because the v2 demo is not optimized (in the HTML side) to just show the remote video when `oncanplay` is fired in the `<video>` element. If you test in v3demo it won't happen.
