### ISSUE TITLE
Can't Publish/Play using Safari 12.1

### ISSUE THREAD

**Issue by ethand91** [versatica/mediasoup-client#73]
Hello,

I am currently facing the issue of not being able to Publish/Play using Safari 12.1.
My current set up is:
Video Codec: H264
Mediasoup Server: 2.6.10
Mediasoup Client: 2.4.9

When trying to publish I get the following error:
> SDP section with a=msid containing trackId [TrackID] not found

When trying to play I get the following error:
> remote track not found

I managed to fix publishing by editing the below file and method:
lib/handlers/sdp/unifiedPlanUtils.js -> findMediaSection
It seemed with Safari 12.1 the media object's "msid" was null i.e not available, I changed this to reference the msid attribute from the media object's ssrc array.

Before:
`m.type === track.kind && m.msid && m.msid.split(' ')[1] === track.id`

After:
`m.type === track.kind && m.ssrcs[1] && m.ssrcs[1].value.split(' ')[1] === track.id`
After the above I was able to publish via Safari 12.1.

To fix playing I edited the below file and method:
lib/handlers/Safari12.js -> addConsumer
It seemed that the transceiver's "mid" was null so I changed the check to check trackIds.

Before:
`const transceiver = this._pc.getTransceivers().find((t) => t.mid === consumerInfo.mid`

After:
`const transceiver = this._pc.getTransceivers().find((t) => t.receiver.track.id === consumerInfo.trackId);`
After the above I was able to play the stream.

Would it be possible to implement the above into mediasoup-client version 2?
I'm no expert on SDP so if anyone has a better way to fix the issue with Safari 12.1 please inform me.

**Comment by ibc** [comment]
Safari 12.1 is the latest stable Safari version, right? Have you changed in "Develop" menu something related to "WebRTC - Unified Plan"?

**Comment by ethand91** [comment]
Yes Safari 12.1 is the latest stable Safari version.

> Have you changed in "Develop" menu something related to "WebRTC - Unified Plan"?
Nope, the settings are set to default.

I managed to reproduce this Mac OS 10.14.4 and iOS 12.2
I found the below issue which seems to be related:
https://github.com/versatica/mediasoup-demo/issues/41

**Comment by ibc** [comment]
Can you try in both https://v2demo.mediasoup.org and https://v3demo.mediasoup.org with same Safari and let me know?

**Comment by ibc** [comment]
Done here and here:

* https://github.com/versatica/mediasoup-client/commit/f9b6fee6a6e196502cd0504340e34365c20205e5
* https://github.com/versatica/mediasoup-client/commit/8bef72f12c6a52446f4fd7e56b5fb2ca46f3cbdb

mediasoup-client 2.4.10 published in NPM.

**Comment by ethand91** [comment]
Thank you for the quick support! 
I'll update tomorrow and let you know the results.

> Can you try in both https://v2demo.mediasoup.org and https://v3demo.mediasoup.org with same Safari and let me know?

I was able to publish/play using the v2demo, however with the v3demo I get the following error:
(The error also occurs using Mac Chrome 73)
`Uncaught (in promise) Error: Cannot find module './data/ja'`
`Uncaught TypeError: Cannot read property '_sendTransport' of undefined`

**Comment by ibc** [comment]
That's not related to mediasoup-client but to the demo app. Probably related to the lib used to choose a random participant name based on browser language. Please check a bit the demo app/lib/index.jsx code, try to figure out where the exact issue is and report an issue in the mediasoup-demo project.
