### ISSUE TITLE
replaceTrack is not working on Safari11

### ISSUE THREAD

**Issue by jiyeyuran** [versatica/mediasoup-client#75]
No Error throw.

**Comment by ibc** [comment]
Sorry, to lazy issue report. It works in Safari 12.1 which is the stable one. And with the given error detail I cannot even investigate which the error is.

**Comment by jiyeyuran** [comment]
I'm using Safari 12.0.2. The detectDevice selects Safari11 as Handler. The video came back if switching back to previous camera. It doesn't throw any error. Perhaps `rtpSender.replaceTrack(track);` is not working on this version.

**Comment by jiyeyuran** [comment]
Also, the other peer is can play video from Safari but the reverse is not working. Both sides are using h264.

**Comment by ibc** [comment]
I'm afraid you are not even telling which mediasoup and mediasoup-client versions you are using, nor even if that's Safari on OSX or iOS.

**Comment by jiyeyuran** [comment]
Sorry for the missing.
1. Safari(12.0.2) on OSX
2. mediasoup v3
3. mediasoup-client v3
Switching camera on Chrome(72) on OSX is working fine.

**Comment by ibc** [comment]
In iOS you need to close the previous webcam track before getting a new one (so before calling replaceTrack). In OSX Safari you may need to do the same. This is not a bug in mediasoup-client.

**Comment by jiyeyuran** [comment]
In mediasoup-demo app, `this._webcamProducer.track.stop();` is called before switching camera.
 
Is there a way to switch camera on the platforms not supporting `replaceTrack`?
Now, I have to call `disableWebcam`, update deviceId, call `enableWebcam` to change camera.

**Comment by ibc** [comment]
> Also, the other peer is can play video from Safari but the reverse is not working. Both sides are using h264.

H264 support is not just about "supporting H264". You must set in the mediasoup Router `mediaCodecs` a H264 codec with a `profile-level-id` value that both endpoints support. And this is tested. If you set a baseline profile ('profile-level-id': '42e01f') H264 works between Safari and Chrome.

BTW this is the H264 profile-level-id matching library used in both mediasoup and mediasoup-client v3: https://github.com/ibc/h264-profile-level-id

> Is there a way to switch camera on the platforms not supporting replaceTrack?

Why are you assuming that `replaceTrack()` does not work in Safari 12.0.2? It works. Or do you get any specific and clear error in the browser console telling that `replaceTrack()` has failed?

**Comment by jiyeyuran** [comment]
Safari is not the point. Because in my country, many browsers are based on the Chromium(<67), `replaceTrack()` is still not working on those versions less than Chrome 67, also not on the react native. Jitsi Meet is using `removeStream`, `addStream` and `renegotiate ` to switch camera, but mediasoup is not working like that. 
It is weird that the console not show any error.
![image](https://user-images.githubusercontent.com/577523/55338318-0cbc2400-54d3-11e9-9449-ae49e5a6989c.png)

**Comment by ibc** [comment]
Yes, I know that in Safari desktop running the mediasoup-demo, when calling `replaceTrack()` the local video is no longer shown. No idea why, but that's not a mediasoup-client bug. The new video is indeed being sent to the SFU.

> many browsers are based on the Chromium(<67), replaceTrack() is still not working on those versions less than Chrome 67, also not on the react native. Jitsi Meet is using removeStream, addStream and renegotiate to switch camera, but mediasoup is not working like that.

You can call `producer.stop()` followed by `transport.produce({track: newVideoTrack }, etc)`.

**Comment by jiyeyuran** [comment]
Thanks a lot.
