### ISSUE TITLE
Desktop sharing with simulcast does not work in Chrome >= 70

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client#79]
As explained in the [issue](https://bugs.chromium.org/p/webrtc/issues/detail?id=10713) reported in Chromium.

**Comment by ibc** [comment]
This is an absolute pain and nobody in Chromium team explains absolutely nothing.

**Comment by mkhahani** [comment]
Starred.

**Comment by ibc** [comment]
Fixed in Chrome Canary 78: https://bugs.chromium.org/p/webrtc/issues/detail?id=10713#c14, so lest's close it.

**Comment by chetanbnaik** [comment]
Hey, I dont think this is completely resolved. In Chrome 83, desktop sharing with simulcast is not working. May be the Chromium guys broke it again.

**Comment by ibc** [comment]
We cannot keep an issue open in mediasoup-client project just due to a Chrome bug. Being honest there are **tons** of cases in which using simulcast + screen sharing in Chrome can produce browser crashes and so on There is a good list of those issues in the libwebrtc tracker.
