### ISSUE TITLE
UnsupportedError: cannot consume this Producer

### ISSUE THREAD

**Issue by jasonkang14** [versatica/mediasoup-client#84]
I am trying to create a consumer in the client-side, but getting an Unsupported Error which says that it cannot consume this Producer. 

I looked at the source code, and the problem is that `remotePayloadType` of `extendedRtpCapabilities.codecs` is undefined while `firstMediaCodec.payloadType` is not

Do you have any ideas to solve the problem?

**Comment by jasonkang14** [comment]
I looked at the source code further, and it looks like it's because there's no RTCPeerConnection to receive data. It's not getting created(?)

**Comment by ibc** [comment]
Please use the mediasoup Discourse Group for questions.
