### ISSUE TITLE
new spread operator in lib

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup-client#95]
3.2.8 includes a spread operator in the driver files in lib and that breaks some older compile tools. Was that a conscious change for the library or just a stray addition?

**Comment by ibc** [comment]
Yes, Object spread operator:

```js
{
  foo: 123,
  bar: "asd",
  ...options
}
```

However this is ECMAScript 6 as told in the [documentation](https://mediasoup.org/documentation/v3/mediasoup-client/design/#features) :)

Honestly I think that any modern JS app must be ready to include ES6 dependencies. Then you can convert your whole app to ES5 by using [terser](https://www.npmjs.com/package/terser), or [gulp-uglify-es](https://www.npmjs.com/package/gulp-uglify-es) (which uses `terser`) or babel with browserify or webpack.
