### ISSUE TITLE
Can open-cli get moved to devDependencies?

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup-client#96]
It's adding a bit of bloat to built packages.

**Comment by artushin** [comment]
Err, I was wrong, that wasn't the package. I think it can still be moved but won't make a difference for size.

**Comment by ibc** [comment]
Indeed it should not be in "dependencies". Thanks for reporting.

**Comment by ibc** [comment]
Fixed in 3.2.10.

**Comment by artushin** [comment]
You removed "open-cli" but added "npm-check-updates"? Isn't that also a dev dep?

**Comment by ibc** [comment]
wowowo.... my fault. Remove in 3.2.11. Thanks!.

**Comment by artushin** [comment]
Thanks!
