### ISSUE TITLE
Firefox 70: ICE failed on recv transport

### ISSUE THREAD

**Issue by jkxyz** [versatica/mediasoup-client#97]
When consuming on a recv transport, I'm seeing the following logs:

```
...

mediasoup-client:Transport consume() | Consumer for RTP probation created +407ms
mediasoup-client:Transport connection state changed to failed +10ms
ICE failed, add a STUN server and see about:webrtc for more details
```

The connection log at `about:webrtc` reads:

```
UDP socket error:Internal error at /builds/worker/workspace/build/src/dom/network/UDPSocketParent.cpp:269 this=0x14f483400
ICE(PC:1574037891072544 (id=32212254723 url=http://localhost:3449/chat)): failed to find default addresses
getifaddrs error e = 1
ICE(PC:1574037891072544 (id=32212254723 url=http://localhost:3449/chat)): peer (PC:1574037891072544 (id=32212254723 url=http://localhost:3449/chat):default) has no stream matching stream PC:1574037891072544 (id=32212254723 url=http://localhost:3449/chat) transport-id=transport_0 - 7302bc83:e71057a0661e208bb2a207cc6f093c45
UDP socket error:Internal error at /builds/worker/workspace/build/src/dom/network/UDPSocketParent.cpp:269 this=0x14f486800
ICE(PC:1574037891072544 (id=32212254723 url=http://localhost:3449/chat)): failed to find default addresses
getifaddrs error e = 1
+++++++ END ++++++++
```

This is occurring in Firefox 70 and 72. The issue does not occur in Firefox 69 (i.e. the media is successfully received). 

This also only occurs for receiving media. I am able to successfully produce media in Firefox and receive it in Chrome. 

I'm using `mediasoup-client@3.3.0`.

**Comment by ibc** [comment]
Definitely it does not happen in the mediasoup-demo using Firefox 70.0.1, so I expect there must be something wrong in your code.

**Comment by cosmosified** [comment]
@jkxyz did you figure out what was wrong with your code??

**Comment by teropa** [comment]
@cosmosified @jkxyz  I'm getting this on Firefox when running on localhost, but not with remote domains. Assume it's a but within Firefox.

**Comment by ibc** [comment]
Firefox property connects ICE for send and recv transports also in local development, not a bug. You may be running Docker or something (you didn't say it) that changes the scenario. Firefox does not support WebRTC over TCP.

**Comment by hpohl** [comment]
For me, the issue occurred when trying to connect locally from within a non-secure iframe. The exact same code runs fine in a secure context.
