### ISSUE TITLE
Error upgrading to 3.3.0 in Angular project

### ISSUE THREAD

**Issue by vpalmisano** [versatica/mediasoup-client#98]
After upgrading to release 3.3.0 I get these errors in an Angular (v8.2.12) project:

`
ERROR in ../node_modules/mediasoup-client/lib/Logger.d.ts:7:9 - error TS1086: An accessor cannot be declared in an ambient context.

7     get debug(): debug.Debugger;
          ~~~~~
../node_modules/mediasoup-client/lib/Logger.d.ts:8:9 - error TS1086: An accessor cannot be declared in an ambient context.

8     get warn(): debug.Debugger;
          ~~~~
../node_modules/mediasoup-client/lib/Logger.d.ts:9:9 - error TS1086: An accessor cannot be declared in an ambient context.

9     get error(): debug.Debugger;
          ~~~~~
../node_modules/mediasoup-client/lib/Producer.d.ts:46:9 - error TS1086: An accessor cannot be declared in an ambient context.

46     get id(): string;
           ~~
`

**Comment by ibc** [comment]
A `.d.ts` file contains the TypeScript definitions of the corresponding TypeScript source file (`.ts`), and this is just used by IDEs that understand TypeScript. The real code is exposed in transpiled `.js` files.

I hope that "issue" (never used Angular so no idea) is related to TypeScript version:

https://stackoverflow.com/questions/58802463/types-sequelize-error-ts1086-an-accessor-cannot-be-declared-in-ambient-context

**Comment by vpalmisano** [comment]
Unfortunately, the latest Angular Compiler requires TypeScript <3.6.0...

Closing this issue since it is related to Angular.

**Comment by ibc** [comment]
Good to know. May I know how this affect writing an Angular project? Can you upgrade your TS compiler version even if Angular installs that version?

**Comment by bigxd123** [comment]
you can but it causes a lot of errors and requires you to ignore them which a lot of people dont want to do.

Angular 9 should support 3.7.

Only way really is to rebuild mediasoup-client with an older typescript version. Is there a specific reason you guys right away updated to 3.7? Its usually best to wait a bit until its widely supported.

**Comment by ibc** [comment]
I don't use Angular so I cannot change this until someone else confirms that it works with current Angular. I'd accept a PR as far as `npm run typescript:build`, `npm lint` and `npm test` run fine with zero warnings/errors.

**Comment by ibc** [comment]
Well, done in 3.3.4.
