### ISSUE TITLE
Chrome 70: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection'

### ISSUE THREAD

**Issue by mkhahani** [versatica/mediasoup-client#99]
Publish and Consume fails on older versions of Chrome:
```
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=extmap-allow-mixed Expects at least 2 fields.
```

**Comment by ibc** [comment]
See this: https://github.com/webrtcHacks/adapter/issues/919

**Comment by ibc** [comment]
To make it clear, this is a bug in Chrome < 71. However I've pushed a change that should avoid the bug in mediasoup-client. Can you pull "v3" branch and try? If it works I'll release a new version.

https://github.com/versatica/mediasoup-client/commit/c5189857ed214cec40950557ae8eb1660075286d?ts=2

**Comment by mkhahani** [comment]
Has been fixed. 👍
